### ISSUE TITLE
cookie的一些建议

### ISSUE THREAD

**Issue by zZPiglet** [chavyleung/scripts#10]
建议cookie的获取可以改成跟[NobyDa](https://github.com/NobyDa/Script/blob/master/QuantumultX/iQIYI-DailyBonus/iQIYI_GetCookie_QX.js)一样，可自动判断是否需要更新，这样可以省去用完注释及更新再取消注释。
以及想问一下腾讯视频里的cookie keeper怎么用呀… 我这边cookie过期感觉有点快。

**Comment by chavyleung** [comment]
cookie keeper经过测试，不起任何有效作用，该过期的还是过期（会删掉）
据反馈，用QQ登录的cookie能用挺久（目前我QQ登录连签5天还没掉），微信登录的貌似1天就掉，玄学。目前没没找到很好的解决办法。

**Comment by zZPiglet** [comment]
好的，谢谢大佬。 我去绑定一个qq😂
