### ISSUE TITLE
豆瓣时间脚本获取不了cookie 了

### ISSUE THREAD

**Issue by iKCloud** [chavyleung/scripts#100]
之前能用，一次成功。但是，在surge卸载重装之后，就死活获取不了cookie 了。豆瓣也试过卸载重装，网页版也试过，就是获取不了。脚本和主机名都是直接复制粘贴过去的，一个字母都不差。请问大佬，这是什么原因？

**Comment by iKangnir** [comment]
在Safari中登录豆瓣手动签到也不提示获取。手动输入网址提示获取成功，但签到脚本不执行。真不知道到底哪出了问题

**Comment by iKangnir** [comment]
2020-04-08 15:34:02.052626 <WARNING> [SGJSVM] An exception was catched while evaluate script dbsj.js: TypeError: undefined is not an object (evaluating 'result.today_status.has_checked'). Line number 18, column: 44
这是执行日志，不明觉厉。

**Comment by Edger** [comment]
@chavyleung 

我发现点 「市集 > 豆瓣时间 > 签到」，没有这个网络请求 `^https:\/\/frodo\.douban\.com\/api\/v2\/niffler\/check_in\/status` 了，应该是这个原因导致获取不到 cookie

**Comment by GideonSenku** [comment]
> @chavyleung
> 
> 我发现点 「市集 > 豆瓣时间 > 签到」，没有这个网络请求 `^https:\/\/frodo\.douban\.com\/api\/v2\/niffler\/check_in\/status` 了，应该是这个原因导致获取不到 cookie

有时间再看看

**Comment by GideonSenku** [comment]
我重新尝试过，里面还是有这条记录的，依然能够获取cookie，不过通知是需要修复一下

**Comment by Edger** [comment]
> 我重新尝试过，里面还是有这条记录的，依然能够获取cookie，不过通知是需要修复一下

获取不了啊，试了很多次

**Comment by GideonSenku** [comment]
> > 我重新尝试过，里面还是有这条记录的，依然能够获取cookie，不过通知是需要修复一下
> 
> 获取不了啊，试了很多次

劝退...

**Comment by GideonSenku** [comment]
豆瓣检测MITM，无解

**Comment by Edger** [comment]
> 豆瓣检测MITM，无解

明白，大佬辛苦了
