### ISSUE TITLE
建议修正网易云音乐获取cookies的rewrite正则或增加提示

### ISSUE THREAD

**Issue by phlinhng** [chavyleung/scripts#114]
我在境外用[README.md](https://github.com/chavyleung/scripts/tree/master/neteasemusic)建议的rewrite规则没办法触发`neteasemusic.cookie.js`。观察log发现根本没有`https://music.163.com/m/*`的请求记录，只有登入时请求过一次`http://music.163.com/m/login`，但是`https://interface.music.163.com/*`的请求有好几个。    
改用以下正则可以在每次进入网页时成功获取cookie：
```
^https?:\/\/interface\.music\.163\.com\/.+ url script-request-header neteasemusic.cookie.js
```
这样应该也行，但是这个规则只有登录时会触发，没有`https://interface.music.163.com/*`好使：
```
^https?:\/\/music\.163\.com\/m\/login url script-request-header neteasemusic.cookie.js
```
建议修改rewrite规则或加上提示，告诉使用者用如果用原本的rewrite不能获取cookie时可以改用以上两种。
客户端: QuantumultX

**Comment by chavyleung** [comment]
^https:\/\/c\.m\.163\.com\/uc\/api\/sign\/v3\/commit

换成这个，有需要的时候再测试下好不好触发
后续有问题再回复本issues
