### ISSUE TITLE
苏宁签到好像跪了

### ISSUE THREAD

**Issue by JKamiy** [chavyleung/scripts#115]
好像红包好的，别的两个都不行，日志见附件
[日志.txt](https://github.com/chavyleung/scripts/files/4534588/default.txt)

**Comment by chavyleung** [comment]
我这一直可以，是新取的 cookie 吗？

**Comment by luanrui** [comment]
> 我这一直可以，是新取的 cookie 吗？

@chavyleung 
surge tf 新的版本都不行了，请求返回的都是html不是json

**Comment by JKamiy** [comment]
> > 我这一直可以，是新取的 cookie 吗？
> 
> @chavyleung
> surge tf 新的版本都不行了，请求返回的都是html不是json

@chavyleung  有希望修一把哇？

**Comment by GideonSenku** [comment]
surge tf版本已修复问题
