### ISSUE TITLE
分期乐其实错误

### ISSUE THREAD

**Issue by hudongxin** [chavyleung/scripts#122]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by hudongxin** [comment]
![CA9025D9-345E-4A5B-A592-1FF5D0FB9AB0](https://user-images.githubusercontent.com/52275745/80852376-b469cf80-8c5a-11ea-874c-f6e6b2e2c318.png)

**Comment by GideonSenku** [comment]
我的号可能被官方ban了,现在有问题也没法修复
