### ISSUE TITLE
电信营业厅签到错误

### ISSUE THREAD

**Issue by sengoku-f** [chavyleung/scripts#124]
前几天都还行,突然就显示
```
[JS Console]: 电信营业厅, data: {"msg":"用户不存在","code":0,"phone":"18xxxxxxxxx"}
```

**Comment by chavyleung** [comment]
更新脚本、更新rewrite 配置、重取cookie 再试

**Comment by kbill4345** [comment]
更新之后，cookie显示获取成功，签到提示错误：
[JS Console]:  电信营业厅
[JS Console]:  电信营业厅 签到失败: SyntaxError: JSON Parse error: Unexpected identifier "undefined"

> 更新脚本、更新rewrite 配置、重取cookie 再试

**Comment by chavyleung** [comment]
> 更新之后，cookie显示获取成功，签到提示错误：
> [JS Console]: 电信营业厅
> [JS Console]: 电信营业厅 签到失败: SyntaxError: JSON Parse error: Unexpected identifier "undefined"
> 
> > 更新脚本、更新rewrite 配置、重取cookie 再试

提供下完整日志

**Comment by sengoku-f** [comment]
> > 更新之后，cookie显示获取成功，签到提示错误：
> 
> > [JS Console]: 电信营业厅
> 
> > [JS Console]: 电信营业厅 签到失败: SyntaxError: JSON Parse error: Unexpected identifier "undefined"
> 
> > 
> 
> > > 更新脚本、更新rewrite 配置、重取cookie 再试
> 
> 
> 
> 提供下完整日志

更新后第二天签到显示

```
[JS Console]: 🔔 电信营业厅
[JS Console]: ❌ 电信营业厅 签到失败: TypeError: undefined is not an object (evaluating ’signinfo.signapp.data.code‘)
```

**Comment by zzemail** [comment]
电信在更新签到功能

sengoku-f <notifications@github.com>于2020年5月9日 周六上午12:58写道：

**Comment by chavyleung** [comment]
电信签到加了参数加密和日期检验，暂时还没找到加密姿势， 暂时无解
