### ISSUE TITLE
圈x米读双账户只有一个增加阅读时间阅读时间

### ISSUE THREAD

**Issue by dlppy** [chavyleung/scripts#131]
两个账户都获取了cookie了，一个加阅读时间，另一个只显示金币数量。作者大佬，想问下，只有surge可以利用py3实现多账号阅读吗？圈x该导出什么数据

**Comment by GideonSenku** [comment]
> 两个账户都获取了cookie了，一个加阅读时间，另一个只显示金币数量。作者大佬，想问下，只有surge可以利用py3实现多账号阅读吗？圈x该导出什么数据

Surge和Thor可以导出配合py3，Qx是自带了生成脚本
