### ISSUE TITLE
建议添加“网上国网”签到，送电费的

### ISSUE THREAD

**Issue by wulifuji** [chavyleung/scripts#133]
`网签到送电费，划算得一塌糊涂，签到就是赚到`

[它总是改名字直接上链接链接](https://apps.apple.com/us/app/%E7%BD%91%E4%B8%8A%E5%9B%BD%E7%BD%91/id1438998315)

**Comment by GideonSenku** [comment]
> `网签到送电费，划算得一塌糊涂，签到就是赚到`
> 
> [它总是改名字直接上链接链接](https://apps.apple.com/us/app/%E7%BD%91%E4%B8%8A%E5%9B%BD%E7%BD%91/id1438998315)

抓不到签到的数据，以及涉及一些敏感暂时不做
