### ISSUE TITLE
合创

### ISSUE THREAD

**Issue by taoziya-ya** [chavyleung/scripts#134]
大佬，合创能否修复一下

**Comment by GideonSenku** [comment]
> 大佬，合创能否修复一下

@danchaw

**Comment by danchaw** [comment]
早已经修复了，修改正则，重新获取cookie

**Comment by danchaw** [comment]
> > 大佬，合创能否修复一下
> 
> 
> 
> @danchaw 


早已经修复了，修改正则，重新获取cookie

**Comment by danchaw** [comment]
> 大佬，合创能否修复一下


已经修复了，修改正则，重新获取cookie
