### ISSUE TITLE
大佬可否添加一个顺丰小当家的签到

### ISSUE THREAD

**Issue by 748170** [chavyleung/scripts#137]
签到都是实打实的现金，满五元自动提现到微信的，还能抽奖，可以搞一下吗？

**Comment by chavyleung** [comment]
app和公众号都搜不到顺丰小当家

**Comment by 748170** [comment]
> app和公众号都搜不到顺丰小当家
商店的app名称叫做年丰小当家。不好意思哈，安卓版本用习惯了，ios平台改名字了。
