### ISSUE TITLE
能否支持一下掌上百科的签到？

### ISSUE THREAD

**Issue by Nergrove** [chavyleung/scripts#14]
掌上百科是一个英语词典分享的网站，签到获得的豆米用来购买用户分享的词典之类的，对于学生用户太有用了，这些词典课哟导入欧陆词典等支持的app试用，十分舒适，有的词典排版精美，很值得收藏。
如果能够支持，万分感谢。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by GideonSenku** [comment]
> 掌上百科是一个英语词典分享的网站，签到获得的豆米用来购买用户分享的词典之类的，对于学生用户太有用了，这些词典课哟导入欧陆词典等支持的app试用，十分舒适，有的词典排版精美，很值得收藏。
> 如果能够支持，万分感谢。
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

可以尝试一下QuanX自动生成，这个需求不是很多人需要

**Comment by nnoyuwan** [comment]
同求
