### ISSUE TITLE
掌上飞车脚本

### ISSUE THREAD

**Issue by chiupam** [chavyleung/scripts#141]
我每天都要手动签到一次更新URL 每天会提示重复签到 但实际上并没有签到成功 有没有人和我这样呀？

**Comment by longgegeaixuexi** [comment]
我也是，基本基本上一天就失效

**Comment by Edger** [comment]
一样，好像cookie有效期只有一天

**Comment by GideonSenku** [comment]
> 一样，好像cookie有效期只有一天

@danchaw 大佬快来看看
