### ISSUE TITLE
618叠蛋糕自动领金币脚本在QX失效

### ISSUE THREAD

**Issue by Nyim1s** [chavyleung/scripts#143]
QX商店版1.0.9，绿勾正版
iOS13.5.1
无论手动还是自动执行脚本，在日志里显示三类错误提示。如下：
1.领取任务，人物太火爆，跳过。
2.errMessage：活动累计签到数上限（凌晨自动执行也这么提示）
3.签到：无效活动！
以上三个提示均大量出现。
另：开启复写后，手动领金币较高几率被提示“活动太火爆”及“网络好像出现了点问题”。关闭复写则不提示
（获取会话有“成功”的提示）

**Comment by Nyim1s** [comment]
该现象本周开始出现。上周没问题。

**Comment by kai2ou** [comment]
以上问题+1

**Comment by chavyleung** [comment]
618 可以弃坑了

**Comment by chouchoui** [comment]
`^https:\/\/api.m.jd.com\/client.action\?functionId=cakebaker_ckCollectScore url script-request-body`
重写这个地址
脚本内容类似下面，反正就两天了，有需求自己改成$prefs.setValueForKey之类的存值取值方法

```js
function getParameterByName(params, name) {
    var match = RegExp('[?&]' + name + '=([^&]*)').exec(params);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

const resBody = $request.body;
console.log("safeStr-------------------");
const safeStrBodyString = getParameterByName(resBody, "body");
const safeStrBodyJson = JSON.parse(safeStrBodyString)
const safeStr = safeStrBodyJson.safeStr;
console.log(JSON.stringify(safeStr));
$done({})
```

需要手动完成一次小精灵任务，然后去日志里面找输出的safeStr字符串

[jd.618.js#L272](https://github.com/chavyleung/scripts/blob/bd262d19a861f6f89ada716bbac0b31805f763ec/jd/jd.618.js#L272)
替换上面这个文件的272行`JSON.stringify({ secretp: $.secretp })`内容为刚才日志输出的 safeStr**字符串**

**Comment by Nyim1s** [comment]
> `^https:\/\/api.m.jd.com\/client.action\?functionId=cakebaker_ckCollectScore url script-request-body`
> 重写这个地址
> 脚本内容类似下面，反正就两天了，有需求自己改成$prefs.setValueForKey之类的存值取值方法
> 
> ```js
> function getParameterByName(params, name) {
>     var match = RegExp('[?&]' + name + '=([^&]*)').exec(params);
>     return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
> }
> 
> const resBody = $request.body;
> console.log("safeStr-------------------");
> const safeStrBodyString = getParameterByName(resBody, "body");
> const safeStrBodyJson = JSON.parse(safeStrBodyString)
> const safeStr = safeStrBodyJson.safeStr;
> console.log(JSON.stringify(safeStr));
> $done({})
> ```
> 
> 需要手动完成一次小精灵任务，然后去日志里面找输出的safeStr字符串
> 
> [jd.618.js#L272](https://github.com/chavyleung/scripts/blob/bd262d19a861f6f89ada716bbac0b31805f763ec/jd/jd.618.js#L272)
> 替换上面这个文件的272行`JSON.stringify({ secretp: $.secretp })`内容为刚才日志输出的 safeStr**字符串**

谢谢！
