### ISSUE TITLE
网易云音乐签到 执行失败

### ISSUE THREAD

**Issue by longgegeaixuexi** [chavyleung/scripts#144]
![4B2C43B6-CA4C-4762-929C-A299C54E8184](https://user-images.githubusercontent.com/34785901/84641605-d62ec580-af2d-11ea-9b9d-0a16ffec0ee9.png)
作者你好，今天网易云音乐签到脚本更新后出现这个问题，执行失败。。

**Comment by chavyleung** [comment]
^https:\/\/music.163.com\/weapi\/user\/level url script-request-body neteasemusic.cookie.js

rewrite 类型需要调整下，再重取 Cookie
`script-request-body`
`script-request-body`
`script-request-body`

注意是script-request-`body`, 不是script-request-`header`

**Comment by longgegeaixuexi** [comment]
非常感谢！现在对啦😁
