### ISSUE TITLE
B站签到脚本执行失败

### ISSUE THREAD

**Issue by tufu9441** [chavyleung/scripts#145]
错误提示如下：
```
iOS 13.5.1 v1.0.10-build313

bilibili, data: {"code":1001,"message":"版本过低,请升级到最新版本","ttl":1}
```
尝试重新获取cookie后依然如此。

**Comment by chavyleung** [comment]
试试卸载 B 站的 App，再签到
`没错，你没看错，我也没写错，就是卸载 B 站`

之前有人反馈人人视频也提示版本过低，卸载 app 解决，重装安装后也能正常签到
可以尝试下（不一定行）

**Comment by tufu9441** [comment]
卸载后试了一下，还是不行，同样的提示。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Chavy <notifications@github.com>
发送时间: Friday, June 19, 2020 11:38:37 AM
收件人: chavyleung/scripts <scripts@noreply.github.com>
抄送: tufu9441 <tufu9441@gmail.com>; Author <author@noreply.github.com>
主题: Re: [chavyleung/scripts] B站签到脚本执行失败 (#145)


试试卸载 B 站的 App，再签到
没错，你没看错，我也没写错，就是卸载 B 站

之前有人反馈人人视频也提示版本过低，卸载 app 解决，重装安装后也能正常签到
可以尝试下（不一定行）

―

**Comment by chavyleung** [comment]
卸载后重装再取一次ck呢

**Comment by tufu9441** [comment]
试了一下依然如此。麻烦问一下，获取cookie是通过浏览器进行的，这跟安装和卸载APP有什么关系吗？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Chavy <notifications@github.com>
发送时间: Friday, June 19, 2020 6:18:08 PM
收件人: chavyleung/scripts <scripts@noreply.github.com>
抄送: tufu9441 <tufu9441@gmail.com>; Author <author@noreply.github.com>
主题: Re: [chavyleung/scripts] B站签到脚本执行失败 (#145)


卸载后重装再取一次ck呢

―

**Comment by chavyleung** [comment]
问题有解决吗？用是的 qx 不

**Comment by tufu9441** [comment]
> 问题有解决吗？用是的 qx 不

还没有解决，用的是QX。

**Comment by chavyleung** [comment]
https://gist.githubusercontent.com/chavyleung/33e1f64fb8f32e8d0c62087f20c6d03b/raw/6687119d8f9036437f5ad402d49dc45f45923113/bilibili.js

用这个试试

**Comment by tufu9441** [comment]
> https://gist.githubusercontent.com/chavyleung/33e1f64fb8f32e8d0c62087f20c6d03b/raw/6687119d8f9036437f5ad402d49dc45f45923113/bilibili.js
> 
> 用这个试试

依然如此，删除了APP后也是。

**Comment by chavyleung** [comment]
尝试下去 b 站绑定手机号码，刚有位老哥反馈绑个手机号就解决了

**Comment by tufu9441** [comment]
还真是这样，好神奇……

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Chavy <notifications@github.com>
发送时间: Tuesday, June 30, 2020 9:44:47 PM
收件人: chavyleung/scripts <scripts@noreply.github.com>
抄送: tufu9441 <tufu9441@gmail.com>; Author <author@noreply.github.com>
主题: Re: [chavyleung/scripts] B站签到脚本执行失败 (#145)


尝试下去 b 站绑定手机号码，刚有位老哥反馈绑个手机号就解决了

―
