### ISSUE TITLE
顺丰速运签到报错

### ISSUE THREAD

**Issue by Tobyyyyt** [chavyleung/scripts#146]
QX1.0.10商店版
手动运行正常
task定时任务报错：

🔔 顺丰速运
2020/06/20 01:02:01:658  <console>    [JS Console]: ❕ 顺丰速运 signapp - response: {"headers":{"Date":"Fri, 19 Jun 2020 17:02:01 GMT","Connection":"keep-alive","Content-Length":"70"},"statusCode":200,"body":"{\"msg\":\"success\",\"code\":0,\"data\":{\"isLogin\":false,\"member_info\":null}}"}
2020/06/20 01:02:01:984  <console>    [JS Console]: ❕ 顺丰速运 getinfo - response: {"headers":{"Date":"Fri, 19 Jun 2020 17:02:01 GMT","Connection":"keep-alive","Content-Length":"70"},"statusCode":200,"body":"{\"msg\":\"success\",\"code\":0,\"data\":{\"isLogin\":false,\"member_info\":null}}"}
2020/06/20 01:02:01:988  <console>    [JS Console]: ❌ 顺丰速运 签到失败: TypeError: null is not an object (evaluating 'signinfo.info.data.member_info.integral')

**Comment by chavyleung** [comment]
现在应该修复了，有问题再回复
