### ISSUE TITLE
请问大佬BoxJs脚本如何使用

### ISSUE THREAD

**Issue by LK373391947** [chavyleung/scripts#147]
已经按照配置要求进行配置，可是打开自带浏览器依旧无法正常显示，希望能够解答，谢谢！

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by chavyleung** [comment]
确认配置无启后，停启一下代理开关

**Comment by LK373391947** [comment]
![66CD2DF8-2516-4F26-BA1E-C9926E9ADC34](https://user-images.githubusercontent.com/49409121/85220984-ab87b580-b3e2-11ea-9d2d-43e6f13c8de4.jpeg)
![962DA594-EA1D-43E2-BE9D-369298F636D6](https://user-images.githubusercontent.com/49409121/85220985-af1b3c80-b3e2-11ea-9aa7-1e915a6b8ed0.jpeg)
配置应该没问题吧，重启手机，开关代理都不行

**Comment by chavyleung** [comment]
页面显示什么，日志输出什么

**Comment by LK373391947** [comment]
> 页面显示什么，日志输出什么

谢谢回复，已经解决了，由于quanX规则原因导致的，经过修改后已经可以正常打开。
