### ISSUE TITLE
分期乐脚本在quan X下持续循环执行

### ISSUE THREAD

**Issue by czmecho** [chavyleung/scripts#152]
在最新的quan X 1.0.11下一直执行停不下来。

**Comment by GideonSenku** [comment]
> 在最新的quan X 1.0.11下一直执行停不下来。

应该不会循环停不下来，根据你设置的cron语法才会执行

**Comment by czmecho** [comment]
> > 在最新的quan X 1.0.11下一直执行停不下来。
> 
> 应该不会循环停不下来，根据你设置的cron语法才会执行

单独执行也是停不下来，问题不大
