### ISSUE TITLE
有道云脚本quantx签到失败

### ISSUE THREAD

**Issue by smilingpoplar** [chavyleung/scripts#153]
iOS 14.0 v1.0.11-build330

🔔有道云笔记, 开始!

❗️有道云笔记, 错误!
JSON Parse error: Unexpected identifier "undefined"

🔔有道云笔记, 结束! 🕛 0.009 秒

**Comment by chavyleung** [comment]
应该是 ck 无效了，重取 ck 应该能解
回头再看看有没其他的姿势可以破

**Comment by chavyleung** [comment]
我这貌似取了 ck 就能正常签，回头再看看换种登录方式吧

**Comment by longgegeaixuexi** [comment]
我也是这样，用之前的签到脚本就正常的

**Comment by chavyleung** [comment]
回头再看看，可能要换一种取 ck 的方式，目前这种就算可以也活不长

**Comment by Microactive** [comment]
我这里也是签到失败
iOS 13.5.1 v1.0.12-build335

有道云笔记, 开始!

有道云笔记, 错误!
JSON Parse error: Unexpected identifier "undefined"

有道云笔记, 结束!  0.01 秒

**Comment by vhvg** [comment]
> 我这貌似取了 ck 就能正常签，回头再看看换种登录方式吧

遇到了同样的问题。
查看发现，在[noteyoudao.js](https://github.com/chavyleung/scripts/blob/master/noteyoudao/noteyoudao.js)中取的四个内容
`$.VAL_login = $.getdata('chavy_login_noteyoudao')`
`$.VAL_sign_url = $.getdata('chavy_signurl_noteyoudao')` 
`$.VAL_sign_body = $.getdata('chavy_signbody_noteyoudao')`  
`$.VAL_sign_headers = $.getdata('chavy_signheaders_noteyoudao')`

第一行变量 `chavy_login_noteyoudao` 并未出现在 [noteyoudao.cookie.js](https://github.com/chavyleung/scripts/blob/master/noteyoudao/noteyoudao.cookie.js)中，且上一版本并无此变量时似乎签到是正常的，不知道是否与此有关。

**Comment by codoha** [comment]
求大佬更新。

**Comment by ArmsZhou** [comment]
有大佬解决了吗

**Comment by xiaoxiaohuangya** [comment]
求大佬更新呀

**Comment by chavyleung** [comment]
有道可以弃坑了
