### ISSUE TITLE
切换会话失败

### ISSUE THREAD

**Issue by liyiecho** [chavyleung/scripts#155]
会话切换, 失败! 原因: TypeError: undefined is not an object (evaluating 'curSession.appName')!

**Comment by chavyleung** [comment]
是不是没保存过会话？

**Comment by liyiecho** [comment]
保存了10个会话，就只有联通签到两个正常运行，剩下的就报错
![IMG_6858(20200626-221804)](https://user-images.githubusercontent.com/5213722/85867246-2db91500-b7fb-11ea-9e84-6e7d6f458b0c.JPG)
![IMG_6859(20200626-221833)](https://user-images.githubusercontent.com/5213722/85867261-3578b980-b7fb-11ea-992c-23a332602903.JPG)

**Comment by chavyleung** [comment]
更新一下脚本再试试

**Comment by liyiecho** [comment]
现在可以正常切换了，感谢修复
