### ISSUE TITLE
QX联通签到失败，Loon 正常

### ISSUE THREAD

**Issue by Marcusias** [chavyleung/scripts#156]
商店版，报错如下
❌ 中国联通 签到失败: TypeError: undefined is not an object (evaluating 'VAL_signurl.endsWith')

**Comment by chavyleung** [comment]
看上去是兼容性问题，你的 iOS 版本是不是比较低？具体是多少？
另外，loon 跟 qx 应该不是同一台 iOS 设备吧？

**Comment by Marcusias** [comment]
> 看上去是兼容性问题，你的 iOS 版本是不是比较低？具体是多少？
> 另外，loon 跟 qx 应该不是同一台 iOS 设备吧？
是同一台设备，iOS版本 13.4.1

**Comment by chavyleung** [comment]
确定 qx 环境下取 ck 了吗

**Comment by Marcusias** [comment]
> 确定 qx 环境下取 ck 了吗

确定获取成功了，我这里也反复尝试好几天了

**Comment by chavyleung** [comment]
有用 BoxJs 不，去看看 chavy_signurl_10010 这个有没值

**Comment by Marcusias** [comment]
> 有用 BoxJs 不，进 BoxJs，内置应用> 中国联通 ，看看 chavy_signurl_10010 这个有没值

BoxJs没有，明天我把全局日志记录下，到时候发出来看看

**Comment by chavyleung** [comment]
从日志看，就是因为chavy_signurl_10010 没有值导致的，这个需要通过获取 ck 才有值
路径是：在 app 里点签到，会提示`获取Cookie: 成功 (每日签到)`
如果没提示这个，就是没获取到

**Comment by Marcusias** [comment]
> 从日志看，就是因为chavy_signurl_10010 没有值导致的，这个需要通过获取 ck 才有值
> 路径是：在 app 里点签到，会提示`获取Cookie: 成功 (每日签到)`
> 如果没提示这个，就是没获取到

问题已解决， 在qx的重写里搜索到了多条10010.js ，删除订阅，重新导入后恢复正常～

**Comment by Marcusias** [comment]
> > 从日志看，就是因为chavy_signurl_10010 没有值导致的，这个需要通过获取 ck 才有值
> > 路径是：在 app 里点签到，会提示`获取Cookie: 成功 (每日签到)`
> > 如果没提示这个，就是没获取到
> 
> 问题已解决， 在qx的重写里搜索到了多条10010.js ，删除订阅，重新导入后恢复正常～
不知道为什么同一url的文件为什么没被覆盖
