### ISSUE TITLE
达美乐的优惠券

### ISSUE THREAD

**Issue by miracomangomanchuria** [chavyleung/scripts#157]
达美乐比萨公众号-优惠资讯-有奖游戏，以前看见有人写浏览器脚本，现在找不到了，好像是控制台调用win()就可以成功领兑换券，这个都不用每天登，cookie能活很久的。

**Comment by androidcn** [comment]
支持  达美乐真的不错

**Comment by GideonSenku** [comment]
需要验证码，没法做
