### ISSUE TITLE
QX联通签到失败

### ISSUE THREAD

**Issue by liyiecho** [chavyleung/scripts#158]
两个号都是都是前几天获取的cookie，用BoxJs保存会话切换，截止到昨天两号都还能签到，今天一个正常，一个失败
![IMG_7086(20200630-080330)](https://user-images.githubusercontent.com/5213722/86075323-5a4e8480-baba-11ea-94dd-ece7f53b942b.JPG)
BoxJs里面看两个会话都有值
![IMG_7105](https://user-images.githubusercontent.com/5213722/86075579-e5c81580-baba-11ea-91f1-86da3799266c.PNG)

**Comment by chavyleung** [comment]
？？解决了？

**Comment by liyiecho** [comment]
上午的时候都是失败，刚才试了下，可以正常签到了，我再观察看看

**Comment by liyiecho** [comment]
今天依然是一个正常签到，另一个失败，但是用联通手机营业厅去签到失败的那个手机号后，再用qx签到就不在显示失败的信息，而是显示已重复签到的信息

**Comment by chavyleung** [comment]
系统弹什么提示出来 ，截图我看看

**Comment by liyiecho** [comment]
先用QX签到时弹出的签到失败信息
<img width="632" alt="1" src="https://user-images.githubusercontent.com/5213722/86267807-d996a200-bbf9-11ea-8f8f-26b3230b8a5a.png">
随后用联通手机营业厅去完成签到后，再用QX签到时弹出的信息
<img width="633" alt="2" src="https://user-images.githubusercontent.com/5213722/86267926-021e9c00-bbfa-11ea-8b03-48579ede773b.png">
