### ISSUE TITLE
大佬有时间看看芒果tv签到谢谢

### ISSUE THREAD

**Issue by dingxinuo** [chavyleung/scripts#16]
大佬可以写一个芒果tv的签到嘛 签到21天可以获得15天会员 有时间大佬可以看一下

**Comment by chavyleung** [comment]
初步抓包感觉可签的可能性不大，后续有空再跟进

**Comment by chavyleung** [comment]
https://github.com/chavyleung/scripts/tree/master/mgtv

测试下

**Comment by dingxinuo** [comment]
可以 谢谢大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chavy <notifications@github.com&gt;
发送时间: 2020年2月13日 02:14
收件人: chavyleung/scripts <scripts@noreply.github.com&gt;
抄送: dingxinuo <916336886@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[chavyleung/scripts] 大佬有时间看看芒果tv签到谢谢 (#16)




https://github.com/chavyleung/scripts/tree/master/mgtv
 
测试下
