### ISSUE TITLE
打开boxjs控制页面导致QX崩溃

### ISSUE THREAD

**Issue by liyiecho** [chavyleung/scripts#161]
boxjs 0.4.0版本，打开boxjs控制页面时，QX会关闭再运行，有时运气好出现一次就能打开控制页面，有时就一直反复，怎么也打不开控制页面。

**Comment by chavyleung** [comment]
qx日志看下

**Comment by liyiecho** [comment]
不知道QX错误日志有没有需要的信息，[日志链接](https://www.dropbox.com/s/mrth4voiuf2twjm/iOS-Quantumult%20X%20Tunnel%202020-07-08--17-41-25-538.log?dl=0)

**Comment by chavyleung** [comment]
日志没有可分析的数据，你说的qx关停是指vpn关了又开吗？找找在关之前的日志看看

**Comment by chavyleung** [comment]
另外，不需要打开boxjs的调试

**Comment by liyiecho** [comment]
> 日志没有可分析的数据，你说的qx关停是指vpn关了又开吗？找找在关之前的日志看看

嗯，VPN关了又开，开了又关，导致无法进入控制页面。之前的日志被我清了，下次遇到的时候再贴上

**Comment by liyiecho** [comment]
现在打开boxjs控制页面时，会出现内存警告，然后QX的VPN关了又开，开了又关，不知道跟boxjs有没有关系
```
2020/07/09 17:33:31:614  <console>    [QTXLogHelper] Log level - warning.
2020/07/09 17:33:31:635  <console>    [QTXPacketTunnelProvider] 58E889B3D073 total running time - 8612889s.
2020/07/09 17:34:09:392  <warning>    [QTXPacketTunnelProvider] Memory warning 11.64MB
2020/07/09 17:34:09:393  <warning>    [QTXPacketTunnelProvider] Memory warning 12.19MB
2020/07/09 17:34:09:401  <warning>    [QTXPacketTunnelProvider] Memory warning 11.30MB
2020/07/09 17:34:09:402  <console>    [JS Console]: 
🔔BoxJs, 开始!

🔔BoxJs, 结束! 🕛 1.181 秒
2020/07/09 17:34:09:405  <warning>    [QTXPacketTunnelProvider] Memory warning 12.38MB

```

**Comment by chavyleung** [comment]
每次打开boxjs都会提示吗？那段时间有同时在运行别的脚本不

**Comment by liyiecho** [comment]
这个时间点没有运行别的脚本。现在每次打开boxjs都会VPN关了又开，运气好是一次，然后进入控制页面了。运气不好进不去控制页面，每次点刷新，都会VPN关了又开，看了日志都有这个提示。

**Comment by chavyleung** [comment]
有打开box的调试吗？如果有，关掉再试试

**Comment by liyiecho** [comment]
box的调试昨天已经关闭了

**Comment by chavyleung** [comment]
订阅了哪些链接，完整发下

**Comment by liyiecho** [comment]
就订阅了两个，链接如下
https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.json
https://raw.githubusercontent.com/liyiecho/scripts/master/box/thinking.boxjs.json

**Comment by chavyleung** [comment]
机型、系统版本分别是多少

**Comment by liyiecho** [comment]
机型 iPhone SE (iPhone 8,4)
系统 iOS 13.5
QX商店版 1.0.12

**Comment by chavyleung** [comment]
已经联系上 qx 作者的协作：配置文件脱敏发来看看，也许规则太多

**Comment by liyiecho** [comment]
[QX配置文件](https://www.dropbox.com/s/iq8wgdrxtg0aefu/quantumult.conf?dl=0)

**Comment by chavyleung** [comment]
尝试把 `BoxJs` 更新到 `0.4.1` 并在侧栏中打开 `修复断连` 开关

**Comment by chavyleung** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/29748519/87103865-caae9000-c288-11ea-83d8-1747d4d20c2d.png">

更新 0.4.1 之后问题还能重现吗？
另外，你把 debug 等级的日志邮件发一下给 qx 作者吧
support+quantumult@crossutility.com

**Comment by liyiecho** [comment]
昨晚更新0.4.1后还是一直进不去，然后我重装了qx，现在能打开控制页面了，目前侧栏中的“修复断连”没有打开，十次有一次VPN断连的样子。

**Comment by chavyleung** [comment]
长按日志图标，把日志等级设置为`debug`，尝试重现 vpn 断连，拿到断连的前后两份日志发给 qx 作者
最后，打开`修复断连`开关，再尝试下能不能重现断连情况

**Comment by liyiecho** [comment]
打开`修复断连`开关后，有时也会出现断连的情况，看了一下跟昨天的一样，内存警告
```
2020/07/10 09:55:08:602  <debug>      [QTXTaskManager] New HTTP session<0x1050879d0>.
2020/07/10 09:55:08:669  <debug>      [QTXTaskManager] New HTTP session<0x10508b560>.
2020/07/10 09:55:08:684  <debug>      [QTXTaskManager] New HTTP session<0x10508ef00>.
2020/07/10 09:55:08:700  <debug>      [QTXTaskManager] New HTTP session<0x10518a6d0>.
2020/07/10 09:55:08:713  <debug>      [QTXTaskManager] New HTTP session<0x105091f50>.
2020/07/10 09:55:08:729  <debug>      [QTXTaskManager] New HTTP session<0x10518c940>.
2020/07/10 09:55:08:744  <debug>      [QTXTaskManager] New HTTP session<0x10518d0f0>.
2020/07/10 09:55:08:759  <debug>      [QTXTaskManager] New HTTP session<0x105190950>.
2020/07/10 09:55:08:812  <warning>    [QTXPacketTunnelProvider] Memory warning 12.23MB
2020/07/10 09:55:08:813  <warning>    [QTXPacketTunnelProvider] Memory warning 12.50MB
2020/07/10 09:55:08:818  <warning>    [QTXPacketTunnelProvider] Memory warning 12.00MB
2020/07/10 09:55:08:820  <console>    [JS Console]: 
🔔BoxJs, 开始!

🔔BoxJs, 结束! 🕛 1.34 秒
2020/07/10 09:55:08:821  <warning>    [QTXPacketTunnelProvider] Memory warning 12.22MB
```
之后VPN断连，日志也记录完毕

**Comment by chavyleung** [comment]
前后两份日志发一下给 qx 作者：support+quantumult@crossutility.com

**Comment by liyiecho** [comment]
QX作者回复说`由于越狱设备的插件注入，导致本就有限制（15M）的 NE 内存占用比非越狱环境高很多。`，我也找到了[解决办法](https://github.com/eycorsican/jetsamproperties)。看来boxjs导致断连，只是巧合，多有打扰。

**Comment by chavyleung** [comment]
嗯，作者也回我邮件说了这个问题。那，修改 NE 内存后使用 boxjs 还会导致 vpn 重连吗？

**Comment by liyiecho** [comment]
修改NE内存后使用boxjs，试了好多次，目前还没有出现VPN断连的情况，倒是有时boxjs弹出操作成功刷新后，东西还是没有更新到最新的。比如手动更新订阅，弹出操作成功，但是刷新后，还是显示之前的更新时间。

**Comment by chavyleung** [comment]
更新到 0.4.2 试试还会不会刷新页面仍不更新问题

**Comment by ps006** [comment]
我的也有上面的问题，只要一刷新boxjs就自动重启VPN，我没越狱，不知道是不是手机系统问题，我的系统还是11.3的，圈叉是1.0.12

**Comment by chavyleung** [comment]
> 我的也有上面的问题，只要一刷新boxjs就自动重启VPN，我没越狱，不知道是不是手机系统问题，我的系统还是11.3的，圈叉是1.0.12

手动重启下qx，把日志等级设置为debug，想办法重现这个问题，再把重启前后两份日志发一下，记得脱敏

**Comment by 663441755** [comment]
> QX作者回复说`由于越狱设备的插件注入，导致本就有限制（15M）的 NE 内存占用比非越狱环境高很多。`，我也找到了[解决办法](https://github.com/eycorsican/jetsamproperties)。看来boxjs导致断连，只是巧合，多有打扰。

![image](https://user-images.githubusercontent.com/61049581/87840209-05d84100-c8d1-11ea-92dc-3d073d7ca106.png)![image](https://user-images.githubusercontent.com/61049581/87840214-0c66b880-c8d1-11ea-8b92-fc785972d7d8.png)

修改以后复制不进去

**Comment by liyiecho** [comment]
@663441755 你可以直接用Filza打开你手机cpu对应的那个plist文件进行修改的（不需要修改全部的`com.apple.jetsamproperties.{Model}.plist`），记得先备份那个文件以防误操作

**Comment by 663441755** [comment]
> @663441755 你可以直接用Filza打开你手机cpu对应的那个plist文件进行修改的（不需要修改全部的`com.apple.jetsamproperties.{Model}.plist`），记得先备份那个文件以防误操作

请问有没有具体步骤。我不知道怎么弄

**Comment by liyiecho** [comment]
@663441755 先查看你手机cpu型号，然后打开filza文件管理器，定位到`/System/Library/LaunchDaemons`文件夹，找到`com.apple.jetsamproperties.XXX`（注：XXX为你的CPU型号前三位）直接点开，点进去后依次点开`Root-Version4-Extension-Override`，往下滑找到`com.apple.networkextension.packet-tunnel`，然后依次修改`ActiveHardMemoryLimit`跟`InactiveHardMemoryLimi`t的值，参考图
![IMG_8083](https://user-images.githubusercontent.com/5213722/87853237-2937d600-c93b-11ea-9f77-a9f41cab7ac9.PNG)

**Comment by faslsgv** [comment]
Xbxbxjx
