### ISSUE TITLE
loon无法获取移动查话费的cookie

### ISSUE THREAD

**Issue by ddasddd** [chavyleung/scripts#165]
在loon上关闭移动查话费获取cookie的脚本，移动app能够正常自动登录用户且各种功能正常，打开cookie脚本不仅用户需要重新登录，而且即使登陆了用户也无法打开话费余额窗口，会显示加载失败。不过这个cookie脚本在quantumultX上能够正常使用。

![IMG_7883](https://user-images.githubusercontent.com/35499162/87616119-f2996a00-c746-11ea-94d4-4f4308db8d07.PNG)
![IMG_7884](https://user-images.githubusercontent.com/35499162/87616133-f88f4b00-c746-11ea-85f2-b02f5f8219ff.PNG)

**Comment by Loon0x00** [comment]
10086.fee.cookie.js
1、脚本运行方式为http-request
2、.finally(() => $.done() 应该为.finally(() => $.done({})，$.done()传参为null，表示为打断请求，传{}表示继续请求

**Comment by chavyleung** [comment]
更新下 `10086.fee.cookie.js` 试试
https://github.com/chavyleung/scripts/commit/bc8909e441ab4890c848d400f1db1a82464d5cd5

**Comment by ddasddd** [comment]
> 更新下 `10086.fee.cookie.js` 试试
> [bc8909e](https://github.com/chavyleung/scripts/commit/bc8909e441ab4890c848d400f1db1a82464d5cd5)

移动界面载入正常了，但是cookie获取成功后，查话费脚本仍然无法使用

![IMG_7887](https://user-images.githubusercontent.com/35499162/87869061-0525d480-c9cf-11ea-8cc6-fcc703a0e358.PNG)

**Comment by chavyleung** [comment]
跑错脚本了吧，你应该执行10086.fee.js, 不是10086.fee.cookie.js

**Comment by ddasddd** [comment]
> 跑错脚本了吧，你应该执行10086.fee.js, 不是10086.fee.cookie.js

是跑错了，用的是nzw的订阅脚本，估计他弄错了，多谢大佬

**Comment by ddasddd** [comment]
> > 跑错脚本了吧，你应该执行10086.fee.js, 不是10086.fee.cookie.js
> 
> 是跑错了，用的是nzw的订阅脚本，估计他弄错了，多谢大佬

https://github.com/chavyleung/scripts/blob/master/10086/10086.fee.cookie.js 里的注释错了，loon那段写的是10086.fee.cookie.js

**Comment by ddasddd** [comment]
> 跑错脚本了吧，你应该执行10086.fee.js, 不是10086.fee.cookie.js

https://github.com/chavyleung/scripts/blob/master/10086/10086.fee.cookie.js 里的注释错了，loon那段写的是10086.fee.cookie.js

**Comment by chavyleung** [comment]
我的锅，已处理

**Comment by ddasddd** [comment]
脚本还是不行
![IMG_7888](https://user-images.githubusercontent.com/35499162/87870314-28ee1800-c9d9-11ea-869f-3c4f31493578.PNG)
