### ISSUE TITLE
v2ex

### ISSUE THREAD

**Issue by OCD0711** [chavyleung/scripts#18]

**Comment by OCD0711** [comment]
v2ex的获取不到cookie没反应

**Comment by chavyleung** [comment]
取不到cookie一般是mitm没正确配置导致的，检查自己的mitm配置是否正确，注意hostname前面要是有#或;请把它去掉，那是注释的意思

**Comment by OCD0711** [comment]
> 取不到cookie一般是mitm没正确配置导致的，检查自己的mitm配置是否正确，注意hostname前面要是有#或;请把它去掉，那是注释的意思

yij
