### ISSUE TITLE
请求添加南方周末APP的签到脚本

### ISSUE THREAD

**Issue by dai640** [chavyleung/scripts#180]
南方系的新闻一直都比较喜欢看，也有深度。

APP每天签到奖励1南瓜，每周累计签到5次，额外奖励10南瓜。南瓜可以抵扣会员订阅费用。

谢谢！

**Comment by GideonSenku** [comment]
已发布测试版

**Comment by GideonSenku** [comment]
> 南方系的新闻一直都比较喜欢看，也有深度。
> 
> 
> 
> APP每天签到奖励1南瓜，每周累计签到5次，额外奖励10南瓜。南瓜可以抵扣会员订阅费用。
> 
> 
> 
> 谢谢！

已发布测试版
