### ISSUE TITLE
音乐网站TRIX签到

### ISSUE THREAD

**Issue by androidcn** [chavyleung/scripts#19]
https://trix360.com/plugin.php?id=dsu_paulsign:sign

**Comment by GideonSenku** [comment]
可以尝试一下QuanX自动生成脚本

**Comment by GideonSenku** [comment]
请求的路径类似这种：`https://dsdlove.com/forum.php?mod=post&action=reply&fid=43&tid=66180&extra=&replysubmit=yes&infloat=yes&handlekey=fastpost&inajax=1`

在手机浏览器进入该网址，切换到网页版，回复一个帖子即可

**Comment by androidcn** [comment]
> 请求的路径类似这种：`https://dsdlove.com/forum.php?mod=post&action=reply&fid=43&tid=66180&extra=&replysubmit=yes&infloat=yes&handlekey=fastpost&inajax=1`
> 
> 在手机浏览器进入该音乐网 网址，切换到网页版，回复一个帖子即可

那么用哪个脚本？

**Comment by GideonSenku** [comment]
> > 请求的路径类似这种：`https://dsdlove.com/forum.php?mod=post&action=reply&fid=43&tid=66180&extra=&replysubmit=yes&infloat=yes&handlekey=fastpost&inajax=1`
> > 在手机浏览器进入该音乐网 网址，切换到网页版，回复一个帖子即可
> 
> 那么用哪个脚本？

用QuanX自己生成属于你的脚本
