### ISSUE TITLE
getPath的一些想法

### ISSUE THREAD

**Issue by ipuppet** [chavyleung/scripts#197]
感觉这样更通俗易懂些，嗯，就这样😜
```js
function getPath(url) {
  // 8是用来略过前面的"https://"，也可改成 `url.indexOf(":")+3`
  // 但我感觉直接写8就可以了，同时略过了http和https，毕竟域名不可能是空的
 if(url.lastIndexOf("/") === url.length - 1)
    return url.slice(url.indexOf("/", 8), -1)
 return url.slice(url.indexOf("/", 8))
}
```
以下为原函数
```js
function getPath(url) {
  // 如果以`/`结尾, 先去掉最后一个`/`
  const fullpath = /\/$/.test(url) ? url.replace(/\/$/, '') : url
  const [, domain] = /https?:\/\/(.*?)\/.*/.exec($request.url)
  return new RegExp(domain).test(url) ? fullpath.split(domain)[1] : undefined
}
```

**Comment by chavyleung** [comment]
代码确实简练多了，感觉两个 return 的代码是不是还有精简的空间？

**Comment by ipuppet** [comment]
加一次变量声明
```js
let end = url.lastIndexOf("/") === url.length - 1 ? -1 : undefined
// 刚才我试了一下slice第二个参数传 undefined 会直接截到最后
return url.slice(url.indexOf("/", 8), end)
```
一行的话可以
```js
return url.lastIndexOf("/") === url.length - 1 ? url.slice(url.indexOf("/", 8), -1) : url.slice(url.indexOf("/", 8))
```
或者
```js
return url.slice(url.indexOf("/", 8), url.lastIndexOf("/") === url.length - 1 ? -1 : undefined)
```
( •̀ ω •́ )✧

**Comment by GideonSenku** [comment]
> 加一次变量声明
> 
> ```js
> let end = url.lastIndexOf("/") === url.length - 1 ? -1 : undefined
> // 刚才我试了一下slice第二个参数传 undefined 会直接截到最后
> return url.slice(url.indexOf("/", 8), end)
> ```
> 
> 一行的话可以
> 
> ```js
> return url.lastIndexOf("/") === url.length - 1 ? url.slice(url.indexOf("/", 8), -1) : url.slice(url.indexOf("/", 8))
> ```
> 
> 或者
> 
> ```js
> return url.slice(url.indexOf("/", 8), url.lastIndexOf("/") === url.length - 1 ? -1 : undefined)
> ```
> 
> ( •̀ ω •́ )✧

忍者代码，写到最后所有代码都变成一行

**Comment by chavyleung** [comment]
我比较偏向“加一次变量声明”，大佬方便提个 PR 吗？

**Comment by ipuppet** [comment]
> 我比较偏向“加一次变量声明”，大佬方便提个 PR 吗？

ok已提交（￣︶￣）↗

**Comment by chavyleung** [comment]
https://github.com/chavyleung/scripts/blob/master/box/chavy.boxjs.js
这个也要改一下

**Comment by ipuppet** [comment]
好的，加上了。没看到还有一个 (；′⌒`)

**Comment by chavyleung** [comment]
感谢大佬
https://github.com/chavyleung/scripts/pull/201
