### ISSUE TITLE
BaiTiao.js报“天天领白条券, 失败! 原因: Error: Cannot find module 'got”

### ISSUE THREAD

**Issue by tarianwei** [chavyleung/scripts#200]
大神，我使用您的baitiao.js测试时报：天天领白条券, 失败! 原因: Error: Cannot find module 'got。请帮忙看下需要修改哪里吗？谢谢

**Comment by chavyleung** [comment]
在 NodeJs 下运行的？

**Comment by GideonSenku** [comment]
> 大神，我使用您的baitiao.js测试时报：天天领白条券, 失败! 原因: Error: Cannot find module 'got。请帮忙看下需要修改哪里吗？谢谢

npm i -D got

**Comment by tarianwei** [comment]
> 在 NodeJs 下运行的？

我在github上运行的

**Comment by tarianwei** [comment]
> > 大神，我使用您的baitiao.js测试时报：天天领白条券, 失败! 原因: Error: Cannot find module 'got。请帮忙看下需要修改哪里吗？谢谢
> 
> npm i -D got
谢谢你，我JS小白，所以不知道如何添加这条命令。下面是我的work.yaml文件
`name: JD_Baitiao

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 1 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run app
              run: npm install
            - run: node JD_BaiTiao.js`

**Comment by GideonSenku** [comment]
> > 在 NodeJs 下运行的？
> 
> 
> 
> 我在github上运行的

这个我还这没有玩过，github workflow的东西
