### ISSUE TITLE
数据倒入错误，导致网页打不开

### ISSUE THREAD

**Issue by YUDIDIFEI** [chavyleung/scripts#202]
不小心把http://boxjs.net/的备份文件导入到http://boxjs.com/，导致现在http://boxjs.com网页无法打开了，需要怎么处理

**Comment by chavyleung** [comment]
解决了吗

http://boxjs.com/revert

**Comment by YUDIDIFEI** [comment]
> 解决了吗
> 
> http://boxjs.com/revert

感谢大佬，现在已经解决了。
