### ISSUE TITLE
趣头条所发现的小问题

### ISSUE THREAD

**Issue by MW8023** [chavyleung/scripts#218]
大佬你好，趣头条很奇怪，单独获取签到cookie的话正常弹窗也显示签到完成，阅读那边显示失败这倒没什么。只是我获取到阅读cookie的话，连弹窗都不弹了看了日志是报错了  不过金币还是照样获取到 只是看不到详情，希望大佬有时间可以瞧瞧是啥问题，同时也感谢大佬的分享与贡献！！！

**Comment by GideonSenku** [comment]
> 大佬你好，趣头条很奇怪，单独获取签到cookie的话正常弹窗也显示签到完成，阅读那边显示失败这倒没什么。只是我获取到阅读cookie的话，连弹窗都不弹了看了日志是报错了  不过金币还是照样获取到 只是看不到详情，希望大佬有时间可以瞧瞧是啥问题，同时也感谢大佬的分享与贡献！！！


原则上阅读通知是一小时一次的
