### ISSUE TITLE
大佬！请求加一个小米有品的签到！感谢🙏

### ISSUE THREAD

**Issue by LiuYuanwork** [chavyleung/scripts#225]
![82E7F392-BFDF-45F1-9BBE-1EFFD81CDDF1](https://user-images.githubusercontent.com/26167263/91164496-afe18f00-e701-11ea-947b-db85efe411a0.png)
大佬！请求加一个小米有品的签到！感谢🙏

**Comment by GideonSenku** [comment]
> ![82E7F392-BFDF-45F1-9BBE-1EFFD81CDDF1](https://user-images.githubusercontent.com/26167263/91164496-afe18f00-e701-11ea-947b-db85efe411a0.png)
> 大佬！请求加一个小米有品的签到！感谢🙏
已经有大佬实现

https://github.com/dompling/Script/tree/master/xiaomiyp
