### ISSUE TITLE
boxjs挂了 进去白屏 或者进不去，除了删loon重装还有别的办法吗

### ISSUE THREAD

**Issue by Joinmogul** [chavyleung/scripts#230]

**Comment by Joinmogul** [comment]
boxjs挂了 进去白屏 或者进不去，除了删loon重装还有别的办法吗

**Comment by chavyleung** [comment]
商店版：http://boxjs.com/revert
测试版：https://chavyleung.gitbook.io/boxjs/advanced/aid

请使用 Loon TF 版！
