### ISSUE TITLE
反馈，10086签到无法获取cookie

### ISSUE THREAD

**Issue by AdoShan** [chavyleung/scripts#231]
[MITM]
wx.10086.cn

[Script]
http-request ^http:\/\/wx.10086.cn\/website\/taskCenter\/index\? script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.cookie.js
http-request ^http:\/\/wx.10086.cn\/website\/taskCenter\/sign\? script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.cookie.js
cron "10 0 0 * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.js

这么写完在10086App签到时无法获取cookie

**Comment by chavyleung** [comment]
我没有移动号码，如果你有条件，可以用 Thor 抓个包给我
1. 杀掉 10086 
2. 打开 Thor 抓包
3. 打开 10086
4. 签到
5. 关掉 Thor 抓包
6. 导出 har （先包含）

**Comment by AdoShan** [comment]
> 我没有移动号码，如果你有条件，可以用 Thor 抓个包给我
> 
> 1. 杀掉 10086
> 2. 打开 Thor 抓包
> 3. 打开 10086
> 4. 签到
> 5. 关掉 Thor 抓包
> 6. 导出 har （先包含）

好的今天已经签到了明天抓了发过来，留个邮箱吧，另外查话费的也无法正常使用，在中国移动（手机营业厅）[https://apps.apple.com/cn/app/%E4%B8%AD%E5%9B%BD%E7%A7%BB%E5%8A%A8-%E6%89%8B%E6%9C%BA%E8%90%A5%E4%B8%9A%E5%8E%85/id583700738?l=en](url)可以获取Cookie但是运行还是显示错误

**Comment by chavyleung** [comment]
chavyleung@gmail.com

10086 和 中国移动 都抓个包吧

**Comment by AdoShan** [comment]
好的，我分开抓

**Comment by AdoShan** [comment]
已发送邮件

**Comment by realyiu** [comment]
> [chavyleung@gmail.com](mailto:chavyleung@gmail.com)
> 
> 10086 和 中国移动 都抓个包吧

可以用了吗？

**Comment by AdoShan** [comment]
> > [chavyleung@gmail.com](mailto:chavyleung@gmail.com)
> > 10086 和 中国移动 都抓个包吧
> 
> 可以用了吗？

你试试咯

**Comment by realyiu** [comment]
> > > [chavyleung@gmail.com](mailto:chavyleung@gmail.com)
> > > 10086 和 中国移动 都抓个包吧
> > 
> > 
> > 可以用了吗？
> 
> 你试试咯

还是不行！

**Comment by gjmdx** [comment]
可以获取ck,但是签到错误,不知道是啥原因

**Comment by 5bizgraud** [comment]
中国移动可以获取cookie,但是不能运行
10086这个客户端连cookie都获取不了

**Comment by immaiker911** [comment]
大佬，请问一下安卓这边可以使用吗，使用你这个教程手机端抓包抓不到~~~~~~~

**Comment by chavyleung** [comment]
10086 好像是下架了
