### ISSUE TITLE
boxjs白屏无法进入

### ISSUE THREAD

**Issue by sengoku-f** [chavyleung/scripts#234]
iphone8p 系统 ios 14 圈x版本1.0.13
日志显示
```
❗️BoxJs, 错误!
TypeError: undefined is not an object (evaluating 'app.keys.forEach')
```

**Comment by chavyleung** [comment]
https://chavyleung.gitbook.io/boxjs/advanced/aid

**Comment by sengoku-f** [comment]
> https://chavyleung.gitbook.io/boxjs/advanced/aid

两个方法都试过了，还是不行

**Comment by chavyleung** [comment]
是添加了订阅或更新了订阅后出现的吗？清掉订阅缓存按道理能让你进去 boxjs 的页面才对

**Comment by sengoku-f** [comment]
> 按道理启用您进去boxjs的页面才对

好像是，最后一条通知是订阅更新成功，然后就进不去了，重启app和手机都不行

**Comment by chavyleung** [comment]
那，你清订阅缓存应该能进去才对

**Comment by sengoku-f** [comment]
> 那，你清订阅缓存应该能进去才对
 
![concact-2020-09-18-133806](https://user-images.githubusercontent.com/31064651/93560220-38c3b180-f9b4-11ea-8e8e-13a396b13afb.png)

**Comment by chavyleung** [comment]
tf 还是商店版？

**Comment by sengoku-f** [comment]
> tf 还是商店版？

商店版

**Comment by chavyleung** [comment]
商店版在这里清

http://boxjs.com/revert

**Comment by sengoku-f** [comment]
> 商店版在这里清
> 
> http://boxjs.com/revert

可以了，感谢大佬

**Comment by sengoku-f** [comment]
发现又挂了，显示白屏，ios 14，圈x版本1.0.14，商店版
```
2020/10/29 13:30:46:117  <console>    [JS Console]: 
2020/10/29 13:30:46:182  <console>    [JS Console]: 
🔔BoxJs, 开始!
2020/10/29 13:30:46:193  <console>    [JS Console]: 
🔔BoxJs, 结束! 🕛 0.01 秒
2020/10/29 13:30:46:193  <console>    [JS Console]: 
2020/10/29 13:30:57:856  <console>    [JS Console]: 
🔔BoxJs, 开始!
2020/10/29 13:30:57:867  <console>    [JS Console]: 
🔔BoxJs, 结束! 🕛 0.011 秒
2020/10/29 13:30:57:867  <console>    [JS Console]: 
2020/10/29 13:34:35:124  <console>    [JS Console]: 
🔔BoxJs, 开始!
2020/10/29 13:34:35:134  <console>    [JS Console]: 
🔔BoxJs, 结束! 🕛 0.01 秒
```

**Comment by chavyleung** [comment]
https://chavyleung.gitbook.io/boxjs/advanced/aid

**Comment by sengoku-f** [comment]
> https://chavyleung.gitbook.io/boxjs/advanced/aid

都试过了，http://boxjs.com/revert 打开也白屏

**Comment by chavyleung** [comment]
应该不存在这样的问题，boxjs 升级到 0.7.58 了吗？如果没有，则按文档上的订阅地址更新一下。

**Comment by ShuaiMakMak** [comment]
我也是，用safari打开是白屏

**Comment by sengoku-f** [comment]
> 应该不存在这样的问题，boxjs 升级到 0.7.58 了吗？如果没有，则按文档上的订阅地址更新一下。

更新了重写，可以了，一直用的nzw9314的重写

**Comment by likemuuxi** [comment]
iPadOS 17.2 (21C5029g)

Quantumult X 1.3.0-781

已清除缓存和备份  还是进不去boxjs.com页面 白屏
已尝试更新

![image](https://github.com/chavyleung/scripts/assets/85612715/cd1a2f4e-82b6-4855-838d-e97ab69858e5)

**Comment by IUswift** [comment]
我的直接都是进不去，日志那里是错误

**Comment by chavyleung** [comment]
> 我的直接都是进不去，日志那里是错误

把错误日志贴出来

**Comment by IUswift** [comment]
![cab0bb4165c64b7d8aa4c690f3f3b8a](https://github.com/chavyleung/scripts/assets/75593539/741c9033-8705-474b-acda-6a845f209436)
已清除缓存和备份 还是进不去boxjs.com页面 白屏
已尝试更新

**Comment by gengleo** [comment]
更新boxjs重写后就打不开了
![image](https://github.com/user-attachments/assets/da171a45-d4f3-49fa-8636-9f52cd4cbbeb)

**Comment by gengleo** [comment]
> 更新boxjs重写后就打不开了
> ![image](https://github.com/user-attachments/assets/da171a45-d4f3-49fa-8636-9f52cd4cbbeb)

![image](https://github.com/user-attachments/assets/499f4088-4c40-4343-a00e-cd9b9c79eb78)
