### ISSUE TITLE
Env get

### ISSUE THREAD

**Issue by BlueskyClouds** [chavyleung/scripts#239]
Env的 get无法处理url中包含(1) 字符会直接返回err

**Comment by chavyleung** [comment]
url 有特殊字符情况下应该把 url  encodeURIComponent 后再传入

**Comment by BlueskyClouds** [comment]
尝试过， encodeURIComponent和encodeURI  均返回Invalid URL

**Comment by BlueskyClouds** [comment]
https://api.day.app/11/(

Error: Invalid URL
    at module.exports (I:\IdeaProject\iqiyi-DailyBonus\node_modules\normalize-url\index.js:60:9)
    at I:\IdeaProject\iqiyi-DailyBonus\node_modules\cacheable-request\src\index.js:43:16
    at get (I:\IdeaProject\iqiyi-DailyBonus\node_modules\got\index.js:98:20)
    at I:\IdeaProject\iqiyi-DailyBonus\node_modules\got\index.js:266:5

**Comment by chavyleung** [comment]
解决了？
