### ISSUE TITLE
什么值得买签到

### ISSUE THREAD

**Issue by kissyuer** [chavyleung/scripts#240]
我想问下为什么我的什么值得买签到总是在登录之前就提示获取到了cookie，然后运行任务就提示没有登录，请问下是什么原因导致的，有什么解决办法吗？谢谢

**Comment by muming88** [comment]
也有这个问题，盼解决

**Comment by o1xhack** [comment]
另外BOXJS写上手机号码/密码还是签到失败

**Comment by chavyleung** [comment]
Close: https://github.com/chavyleung/scripts/commit/5b8369d605be1b6996a9ff918287ecd4d3316972

更新[什么值得买]: 移除 APP 端签到 (原因: APP 端增加了参数校验)
