### ISSUE TITLE
加油广东签到报错，什么值得吗APP签到失效

### ISSUE THREAD

**Issue by Jone2008** [chavyleung/scripts#241]
加油广东签到报错，但是暂时签到还是成功的。值得买签到报告显示网页版签到正常，APP 0/0。
请大佬有空看看修复下，感谢大佬

**Comment by qhq** [comment]
app匹配网址变了好像，以前是api，现在是user-api，得等更新了

**Comment by chavyleung** [comment]
加油广东好像容易失效，充坑
大妈 app 端签到也失效了，新接口有校验，弃坑
