### ISSUE TITLE
bilibili签到脚本错误

### ISSUE THREAD

**Issue by 123456qewret** [chavyleung/scripts#242]
更新了最新的直播cookie显示账号未登录
iOS 14.2 v1.0.15-build395

bilibili, data: {"code":-101,"message":"账号未登录","ttl":1}

**Comment by qliang0816** [comment]
一样，有解决吗

**Comment by muzili5678** [comment]
没

在2020年11月22日星期日，LeoQin <notifications@github.com>认为：

**Comment by cpu-sd** [comment]
相同的错误，解决方式仅供参考：
1.打开mitm选项，【生成证书】->【配置证书】
2.Safari打开哔哩哔哩网站的时候，使用www.bilibili.com网址（rewrite_local里面的匹配规则是www|live匹配）
这样在safari打开的时候QX就能匹配到cookie了
