### ISSUE TITLE
什么值得买App签到报错

### ISSUE THREAD

**Issue by HelloWorldCll** [chavyleung/scripts#243]
您好，用BoxJs手撕账号签到的，App签到失效报错，请问是什么问题。谢谢![image](https://user-images.githubusercontent.com/28375991/96807922-53bd9180-144a-11eb-8b44-1ac941ab7e17.jpeg)

**Comment by chenyz1984** [comment]
解决了吗？

**Comment by HelloWorldCll** [comment]
> 解决了吗？

没有哦

**Comment by chavyleung** [comment]
Close: https://github.com/chavyleung/scripts/commit/5b8369d605be1b6996a9ff918287ecd4d3316972

更新[什么值得买]: 移除 APP 端签到 (原因: APP 端增加了参数校验)
