### ISSUE TITLE
能否在Env.js里面增加对PUT的支持

### ISSUE THREAD

**Issue by doherty88** [chavyleung/scripts#253]
我这本地一个商城的小程序我想自己写个每日签到的脚本，但是抓包发现他们使用的PUT request进行签到操作，能否在Env.js里面增加对PUT的支持呢？谢谢

**Comment by chavyleung** [comment]
可以，有空我看看

**Comment by GideonSenku** [comment]
https://github.com/chavyleung/scripts/commit/88f06a77d6bf8df093ffea9fdc171ae72b2073fb
