### ISSUE TITLE
quantx全局备份后粘贴导入，空白（只显示BoxJS字样）

### ISSUE THREAD

**Issue by smilingpoplar** [chavyleung/scripts#258]
最新的v0.7.58

**Comment by chavyleung** [comment]
https://chavyleung.gitbook.io/boxjs/advanced/aid

**Comment by smilingpoplar** [comment]
在抹掉全局备份后可以重新进入boxjs页面。但全局备份后再导入备份，又会导致白屏。我只有1个全局备份，想在另一手机恢复备份，试了在本机恢复备份一样白屏

**Comment by id77** [comment]
有可能ios某些文本编辑，在输入或粘贴内容时，符号会被改变，从而导致你的备份出现问题。

比如"会变”，英文符号会变中文。
我在Working Copy 和 QuantumultX 遇到过，WC在复制JSON到.txt会出现，QX以前配置打开的时候会出现，经我向开发者反馈，很早之前已经修复。

不过ios的备忘录则没遇到过，推荐你使用备忘录进行保存备份。

不知道你用的什么保存备份内容。


发自我的iPhone

**Comment by smilingpoplar** [comment]
并没有用到文本编辑器，在浏览器boxjs页面，全局备份，复制，然后同一页面导入

> 有可能ios某些文本编辑，在输入或粘贴内容时，符号会被改变，从而导致你的备份出现问题。 比如"会变”，英文符号会变中文。 我在Working Copy 和 QuantumultX 遇到过，WC在复制JSON到.txt会出现，QX以前配置打开的时候会出现，经我向开发者反馈，很早之前已经修复。 不过ios的备忘录则没遇到过，推荐你使用备忘录进行保存备份。 不知道你用的什么保存备份内容。 发自我的iPhone
> […](#)
> 在 2020年11月15日，下午5:46，YangLe ***@***.***> 写道： ﻿ 在抹掉全局备份后可以重新进入boxjs页面。但全局备份后再导入备份，又会导致白屏。我只有1个全局备份，想在另一手机恢复备份，试了在本机恢复备份一样白屏 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chavyleung** [comment]
据反馈，QuanX 商店版有个 issue 引起的，TF 版正常。

**Comment by smilingpoplar** [comment]
那就等quantx更新。或者有什么workaround？

**Comment by id77** [comment]
> 那就等quantx更新。或者有什么walkaround？

自己排查，原因都不知道，更新啥更...
我就是QuantumultX，正常得很，0.7.58我一直在用，这期间QX都迭代好多个版本了，依然正常

**Comment by smilingpoplar** [comment]
@id77 你是作者吗？你没问题不代表别人没问题。不要做没意义的插话。我三个设备都是过了，同样症状。

**Comment by id77** [comment]
> @id77 你是作者吗？你没问题不代表别人没问题。不要做没意义的插话。我三个设备都是过了，同样症状。

那是你三设备都用了同样的备份吧，你自己可能家了什么数据、订阅有问题，你不是没提供吗？一直想着别人解决？不提供，不是应该自己排查？

你觉得是QX的问题？这话在boxjs这里问，就有意义了？

你不应该提供资料去给QX开发者？

如果是boxjs数据的原因，你自己又没找到，你可以私下发数据给予boxjs的开法人员排查，而不是问这种无意义的问题。

**Comment by smilingpoplar** [comment]
> 你觉得是QX的问题？这话在boxjs这里问，就有意义了？

是 @chavyleung 说的，我哪知道

**Comment by id77** [comment]
> > 你觉得是QX的问题？这话在boxjs这里问，就有意义了？
> 是 @chavyleung 说的，我哪知道

据我了解，Loon也有用户出现这种情况，QX最新TF和Loon还有boxjs黑屏的。但我用着正常。

chavyleung 他没用QX来着，据反馈而已。

**Comment by chavyleung** [comment]
> 那就等quantx更新。或者有什么walkaround？

有在用`中青自动阅读`吗? 如果有：
1. 在`boxjs`内进入`中青自动阅读` 
2. 清空掉 `zqgetbody_body`与`zqgetbody_body1` 的值
3. 再尝试`导出`与`导入`

**Comment by chavyleung** [comment]
有问题再回复
