### ISSUE TITLE
腾讯视频cookie更新机制

### ISSUE THREAD

**Issue by Liquor030** [chavyleung/scripts#26]
网页访问v.qq.com 登陆账号
刷新--抓包
有个链接为https://access.video.qq.com/user/auth_refresh?xxxxxxxxx
将cookie等信息记录，
在需要签到时重放请求，返回的header里就是刷新好的cookie。

希望以上这些能对你有帮助。

我发现一个有趣的东西，央视频app的签到cookie刷新机制和腾讯视频貌似是同一种方法，可惜抓取不到他刷新cookie的请求。

**Comment by mrhuangbh** [comment]
另外，我感觉通过腾讯的云函数类似的服务，通过python能够更好的解决签到问题，哈哈

**Comment by chavyleung** [comment]
auth_refresh后面的参数是固定的还是每次都变的？

**Comment by chavyleung** [comment]
目前情况是: 用qq登录，连签近1个月了，用微信登录的1天就失效

**Comment by Liquor030** [comment]
不变

**Comment by Liquor030** [comment]
每个账号后面都是不一样，得抓这个链接，然后直接用它返回的cookie

**Comment by chavyleung** [comment]
明天研究下，如果不变的话每次请求一下获取新的cookie就能永远签下去了

**Comment by Liquor030** [comment]
👌

**Comment by chavyleung** [comment]
我刚分析了下, `auth_refresh`其实只更新了下Cookie中的登录时间戳, 其他信息没有任何变更. 

所以我尝试了下直接通过正则替换cookie中的时间戳来实现同样效果: 
```js
cookie.replace(/vqq_login_time_init=[^;]*/, `vqq_login_time_init=${timestamp}`)
```

目前在测试中...明天我再观察下其他Cookie信息会不会刷新

**Comment by Liquor030** [comment]
一般都是刷新一个类似vusession的值。例如qq登陆的是vqq_vusession，微信没测试过，不过应该差不多。那个时间戳腾讯那边貌似不检测，不影响的

**Comment by chavyleung** [comment]
是的，微信登录的cookie是没有任何时间相关的cookie信息的，所以我这用微信一直能连签。

但刚问了一圈，发现有朋友微信也会失效，我怀疑这跟多处登录有关系，如果是多处登录，仅更新时间戳是不够的，所以可能还是得用auth_refresh返回的值来完整覆盖（看来想偷个懒还是不行）

**Comment by Liquor030** [comment]
微信应该也能抓到auth_refresh的链接吧

**Comment by chavyleung** [comment]
可以的，不管微信还是QQ，只要是从页面抓就能抓到auth_refresh
回头我改下代码自测一下

**Comment by Liquor030** [comment]
那就ok，不过我用的是腾讯的云函数，定时触发脚本就行啦，代码可以参考https://github.com/Liquor030/scf_sign/blob/master/tx_video.py

**Comment by chavyleung** [comment]
ok, 谢谢

**Comment by chavyleung** [comment]
央视频的refresh_token应该是app内生成的，不是通过请求得来的，这个应该无解

**Comment by Liquor030** [comment]
确实，感觉央视频是腾讯的程序员搞的app，太像了，哈哈哈

**Comment by chavyleung** [comment]
应该是外包给腾讯干的
