### ISSUE TITLE
商店版loon访问BoxJS只显示boxjs字样，清除备份、清除订阅脚本都运行了都无效

### ISSUE THREAD

**Issue by zlq** [chavyleung/scripts#260]
报错日志为：TypeError: null is not an object (evaluating 'sub.url')

**Comment by zlq** [comment]
我自己已经解决了，导入订阅的时候直接导入了null对象进订阅列表，导致白屏、黑屏。写一个接口把订阅异常信息修复就可以了。导入订阅为null，主要是导入的时候没有判空导致的。
https://raw.githubusercontent.com/zlq/Loon/master/BoxJs.js

**Comment by HweeJohn** [comment]
圈x的有没有办法解决

**Comment by chavyleung** [comment]
这个问题是网络异常导致的吗？

**Comment by HweeJohn** [comment]
> 这个问题是网络异常导致的吗？

并不是，感觉是导入了null空白格式一样的
