### ISSUE TITLE
新手求教程，第一次接触。

### ISSUE THREAD

**Issue by s1sunny** [chavyleung/scripts#267]
各路热心大神好，第一次接触这种脚本。还不会使用，能简单出个教程指点一下吗？
我使用的是IOS，软件有圈X
也有安卓机。
谢谢。

**Comment by hacken156026692** [comment]
听友人推荐的，进来看到这个大宝库。请问安卓能用吗？？能把这些文件在termux里运行吗？？

**Comment by erro-life** [comment]
https://chavyleung.gitbook.io/boxjs/

**Comment by chavyleung** [comment]
目前只能运行在 Surge、 QuanX 、Loon、小火箭等 APP 上
