### ISSUE TITLE
贴吧签到

### ISSUE THREAD

**Issue by yyingx** [chavyleung/scripts#27]
能不能小升级一下，把签到明细也显示出来，目前发现有一个签到不成功

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by chavyleung** [comment]
一直签不成功还是偶尔签不成功

如果是偶尔签不成功：你不应该关注哪个签不成功, 让脚本执行多次就行，一次不成功就两次、三次
```properties
# 参考我的, 每天00:01, 00:05, 00:06各运行一次, 一般就能全部成功
1,5,6 0 * * * chavy/tieba/tieba.js
```

如果每天都固定有个吧签不成功: 去查下日志，看下是哪个贴，把吧名发给我

**Comment by yyingx** [comment]
![image](https://user-images.githubusercontent.com/10001627/73866939-b0f3c180-4880-11ea-80a0-b795e27691fb.jpg)
那个是贴吧的问题。其实吧，我想要这种界面

**Comment by chavyleung** [comment]
这种样式已经有大佬做出来了，可以考虑下用他的脚本
我个人比较喜欢简约风格，所以不考虑做成这种通知形式了

**Comment by yyingx** [comment]
👌
2020年2月6日 +0800 AM1:41 Chavy <notifications@github.com>，写道：
