### ISSUE TITLE
loon通过局域网访问并未成功

### ISSUE THREAD

**Issue by RockZhou8** [chavyleung/scripts#276]
loon版本：商店版 最新版 2.1.4 (221)
网络共享已开启 端口7222
http://192.168.1.214:7222
ios的loon在start之后，通过浏览器访问file:///C:/scripts-master/box/chavy.boxjs.html?baseURL=http://192.168.1.241:7222

ios设备上有loon的两条提示发现新设备，一个是设备自己的ip 192.168.1.241,一个是我本地的PC 192.168.1.66
但是网页还是空白的，loon也自动stop了

**Comment by monkey-sking** [comment]
现在loon支付局域网访问boxjs了？

**Comment by RockZhou8** [comment]
> 现在loon支付局域网访问boxjs了？
https://chavyleung.gitbook.io/boxjs/advanced/pc

通过 PC 访问
BoxJs - v0.7.5 开始，页面已经抽提出一个完整的、可运行的 HTML 文件。这意味着，我们可以单独运行这份 HTML。如：电脑上直接双击运行、部署在自己的服务器上……

**Comment by monkey-sking** [comment]
> > 现在loon支付局域网访问boxjs了？
> 
> https://chavyleung.gitbook.io/boxjs/advanced/pc
> 
> 这里提到loon配置网络共享端口号。。。
> 但是下面的确没说loon怎么访问。。。
> 所以是还不行吗？那配置共享作用是啥啊

我试了下，也是不行

**Comment by monkey-sking** [comment]
> > 现在loon支付局域网访问boxjs了？
> 
> https://chavyleung.gitbook.io/boxjs/advanced/pc
> 
> 这里提到loon配置网络共享端口号。。。
> 但是下面的确没说loon怎么访问。。。
> 所以是还不行吗？那配置共享作用是啥啊

是电脑使用手机的IP和端口当代理，然后就可以访问了

**Comment by chavyleung** [comment]
> > > 现在loon支付局域网访问boxjs了？
> > 
> > 
> > https://chavyleung.gitbook.io/boxjs/advanced/pc
> > 这里提到loon配置网络共享端口号。。。
> > 但是下面的确没说loon怎么访问。。。
> > 所以是还不行吗？那配置共享作用是啥啊
> 
> 是电脑使用手机的IP和端口当代理，然后就可以访问了

正解
