### ISSUE TITLE
请教大佬boxjs的原理是什么？

### ISSUE THREAD

**Issue by magic3584** [chavyleung/scripts#282]
boxjs 怎么来的？为什么 qx 里的脚本能被 boxjs 里参数控制？自己写的话要怎么入手？

**Comment by chavyleung** [comment]
如果深入聊的话：篇幅可能会过长, 我尽量说人话 [狗头]

开始之前你可能需要补充一些基础知识：
https://manual.nssurge.com/book/understanding-surge/cn/#tlshttps-%E4%B8%8E-mitm

# 问：BoxJs 原理是什么?
**最初**，BoxJs 是通过重写 (Rewrite) 的方式实现的 (也就是类似去广告的原理)
当用户访问一个**存在**的网站时，脚本把网站返回的内容完全替换成 BoxJs 的页面
缺点：这个网站必须是存在并可访问的，如果网站挂，BoxJs 也会跟着访问不了。

**后来**，得益于代理应用实现了**抢答**机制
用户在访问 http://boxjs.net 时，不会真的发请求到 boxjs.net，而是直接运行脚本，由脚本来直接返回 "造假" 的网站。
这就类似在代理应用内搭了个类似 Nginx、Tomcat 的服务，访问特定域名时由脚本来响应 HTTP 请求。 

# 问：为什么 qx 里的脚本能被 boxjs 里参数控制？
qx 提供了全局的 getter、setter 接口，通过接口可以实现持久化数据的`存`与`取`

```javascript
// 在 BoxJs 里存：
$.set('baidu_cookie', 'xxx')

// 自然就可以在脚本里取
$.get('baidu_cookie') => xxx
```

# 问：自己写的话要怎么入手
如果你问的是脚本怎么写，可以先从 qx 的[官方示例](https://github.com/crossutility/Quantumult-X)入门

**Comment by magic3584** [comment]
感谢大佬给的渔，大佬技术好人又 nice
