### ISSUE TITLE
boxjs匿名订阅 格式错误

### ISSUE THREAD

**Issue by amumu2008** [chavyleung/scripts#283]
大佬，推荐订阅后，提示匿名订阅（0） 格式错误
添加各种订阅都不成功

**Comment by wislin918** [comment]
我也这种情况，只有1个lxk0301的订阅能打开，不知道是不是节点的问题

**Comment by CreamK** [comment]
解决了吗

**Comment by chavyleung** [comment]
把你们添加的订阅地址贴出来看看

**Comment by amumu2008** [comment]
https://raw.githubusercontent.com/lxk0301/jd_scripts/master/lxk0301.boxjs.json     这个

**Comment by chavyleung** [comment]
这个订阅添加不成功么，试试开全局再添加或刷新订阅

**Comment by amumu2008** [comment]
不止这个   都不成功         全局模式就是右下角的圈圈  改成黄色？      手机没任何翻墙软件及代理    就靠圈X自带的  。。

**Comment by wislin918** [comment]
https://raw.githubusercontent.com/toulanboy/scripts/master/toulanboy.boxjs.json
https://raw.githubusercontent.com/NobyDa/Script/master/NobyDa_BoxJs.json
https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/evilbutcher.boxjs.json
https://raw.githubusercontent.com/photonmang/quantumultX/master/photonmang.boxjs.json
https://raw.githubusercontent.com/xingliuchao/jd/main/box.json 
我是以上订阅都报错，打开以上订阅的仓库是提示浏览器打不开该网页，无法与服务器建立安全的连接，我圈X只用来跑脚本，用的其他vpn软件。之前正常的时候，vpn软件都不需要打开。


倪林
常州亿晶光电科技有限公司
江苏省常州市金坛区尧塘镇金武路18号
邮编：213200
Email：nilin@eging.cn
手机：15051907341
固话：0519-82588660
 
发件人： Chavy
发送时间： 2020-12-31 08:51
收件人： chavyleung/scripts
抄送： wislin918; Comment
主题： Re: [chavyleung/scripts] boxjs匿名订阅 格式错误 (#283)
把你们添加的订阅地址贴出来看看

**Comment by chavyleung** [comment]
这个问题，还存在吗？

**Comment by chavyleung** [comment]
有问题后续再回复本 Issue.

**Comment by baigougou** [comment]
https://raw.githubusercontent.com/ZhiYi-N/Private-Script/master/ZhiYi-N.boxjs.json 还有报错

**Comment by chavyleung** [comment]
> https://raw.githubusercontent.com/ZhiYi-N/Private-Script/master/ZhiYi-N.boxjs.json 还有报错

我这正常，尝试在 内置应用 > 偏好设计 > 抹掉缓存 再刷新缓存试试

**Comment by Yushao88** [comment]
清楚缓存也试过了 还是没添加成功 格式错误

**Comment by pdszpj** [comment]
如下这个地址也说格式错误https://jdsharedresourcescdn.azureedge.net/jdresource/lxk0301.boxjs.json
