### ISSUE TITLE
请问用nodejs运行电信签到应该把号码和cookie写在哪里?

### ISSUE THREAD

**Issue by GitCourser** [chavyleung/scripts#286]
rt

**Comment by CheYanShang** [comment]
我也卡在“请在 BoxJs 填写手机号码!”

这个BoxJs到底在哪儿啊？

**Comment by chavyleung** [comment]
https://chavyleung.gitbook.io/boxjs/

**Comment by hacken156026692** [comment]
我也想咨询一下，我用nodejs的，大神你这个脚本，能在nodejs上运行吗？谢谢！

**Comment by chavyleung** [comment]
> 我也想咨询一下，我用nodejs的，大神你这个脚本，能在nodejs上运行吗？谢谢！

BoxJs 暂不能运行在 NodeJs 环境，但部分签到脚本可以。
