### ISSUE TITLE
boxjs打开空白，已尝试过急救的方法

### ISSUE THREAD

**Issue by yogayyy** [chavyleung/scripts#288]
![929AE424-38F9-43D3-82C1-7851EA10D4AB](https://user-images.githubusercontent.com/50315632/103716647-8cf3af80-4ffe-11eb-9545-1d2ade2c37c7.png)
打开就是这样的.....手动执行过急救里写的两条代码后还是没啥用，求大佬解答一下，谢谢。👀

**Comment by chavyleung** [comment]
运行日志有报错不

**Comment by yogayyy** [comment]
> 运行日志有报错不

BoxJs, 开始!
09:21:12.397404 
🔔BoxJs, 结束! 🕛 0.197 秒
09:21:12.397439 
2021-01-06 09:21:12.958690 <NOTIFY> [SGJSVM] [Rewrite: BoxJs]

没报错，就是打开什么都没有...清备份和缓存后偶尔会能出菜单，但之前的订阅全都格式错误什么，而且不能操作，随便点一下就继续什么都没有了😂

**Comment by yogayyy** [comment]
重启后好像可以了，不过需要手动一个个把原来的订阅添加进去，恢复备份不行，迷迷糊糊解决了，打扰大佬啦～🎉
