### ISSUE TITLE
字幕组的签到对永久金至尊会员无效，希望修正或备注

### ISSUE THREAD

**Issue by leon-zhu** [chavyleung/scripts#29]
Quantumult X 1.05

**Comment by chavyleung** [comment]
能具体描述下是怎样无效吗？签到有通知吗？日志有输出吗？

**Comment by leon-zhu** [comment]
> 能具体描述下是怎样无效吗？签到有通知吗？日志有输出吗？

具体表现如下：1. 首先tip中会显示undefined  2. 其次登录到app中会发现没有签到成功，连续3天都是这样
如下图所示：
![zimuzu_01_new](https://user-images.githubusercontent.com/37819685/74035974-57ad9e80-49f6-11ea-92f2-465d0bd5ac2f.jpg)
![zimuzu_02_new](https://user-images.githubusercontent.com/37819685/74036000-63996080-49f6-11ea-88f5-e9d18c78e5ae.jpg)

**Comment by chavyleung** [comment]
帮确认下：登录网页看看登录天数有没加

**Comment by leon-zhu** [comment]
> 帮确认下：登录网页看看登录天数有没加

我明天再确认下，因为今天是登录上去手动签到的，天数确实是217

**Comment by chavyleung** [comment]
![D43B3C3D-F3BF-4BE2-8C0E-CCB8728F3761](https://user-images.githubusercontent.com/29748519/74039637-27b5c980-49fd-11ea-9d88-89779cea1dc3.png)
看小字，app的连签跟网页不关联，晚点看能不能整个双端签到

**Comment by chavyleung** [comment]
https://github.com/chavyleung/scripts/tree/master/zimuzu

已经调整通知样式，并增加APP端签到，测试

**Comment by leon-zhu** [comment]
已测试，没有问题，谢谢大佬支持

**Comment by Edger** [comment]
字幕组 app 端签到失败

<img width="416" alt="截屏2020-02-1112 54 05" src="https://user-images.githubusercontent.com/18591042/74212113-a21c6d00-4ccd-11ea-94b3-dea4d185d72b.png">

2020/02/11 12:52:01:569  <console>    [JS Console]: 字幕组, signweb - data: {"status":1,"info":"","data":{"userinfo":{"kuozhan_group_info":null,"main_group_name":"\u9ec4\u91d1\u4f1a\u5458","uid":"6847988","free_tran":"0","avatar_t":"http:\/\/tu.jstucdn.com\/ftp\/avatar\/f_noavatar_t.gif","point":"1121","nickname":"Edgers","common_group_name":"\u9ec4\u91d1\u4f1a\u5458","sex":"0","avatar_s":"http:\/\/tu.jstucdn.com\/ftp\/avatar\/f_noavatar_s.gif","avatar_m":"http:\/\/tu.jstucdn.com\/ftp\/avatar\/f_noavatar_m.gif","group_name":"\u9ec4\u91d1\u4f1a\u5458","yyets_group":0},"usercount":{"cont_login":"67","thread":"0","unread_msg":"0","unread_sys":"0"},"post":"","navbar":{"a":"<li channel=\"fav\"><a href=\"\/user\/fav\">\u6536\u85cf<\/a><\/li>"},"upgrade_day":23}}
2020/02/11 12:52:02:060  <console>    [JS Console]: 字幕组, signapp - data: {"status":1021,"info":"\u8bf7\u5148\u767b\u5f55","data":""}
