### ISSUE TITLE
BoxJs 收藏应用处的排序按钮（上移/下移）无法使用

### ISSUE THREAD

**Issue by YM1099** [chavyleung/scripts#290]
表现为点击上移/下移后无事发生，
或点击想要移动的应用上移/下移，实际移动的却是另一个应用。

代理软件为 QX 商店最新版，BoxJs 版本 0.7.62，两台手机上都有问题。

**Comment by chavyleung** [comment]
把 BoxJs 升至 v0.7.76 +
进入 `偏好设置`，运行`抹掉：收藏应用`

刷新下页面后，进入 BoxJs 并重新收藏和排序看是否正常。

**Comment by YM1099** [comment]
> 把 BoxJs 升至 v0.7.76 +
> 进入 `偏好设置`，运行`抹掉：收藏应用`
> 
> 刷新下页面后，进入 BoxJs 并重新收藏和排序看是否正常。

升级、抹除后重新收藏，可以正常移动了
