### ISSUE TITLE
什么值得买app签到错误

### ISSUE THREAD

**Issue by androidcn** [chavyleung/scripts#292]
错误
🔔什么值得买, 开始!

❗️什么值得买, 错误!
TypeError: null is not an object (evaluating '_data.data.checkin_status')

==============📣系统通知📣==============
什么值得买
PC: 成功, APP: 0/1
累计: 12次, 经验: 2843, 金币: 3, 积分: 47
点击查看详情

anxx: 失败. undefined

**Comment by nianyuguai** [comment]
最新App的登录请求已经修改了，APP端每次请求都要带sign参数，而且每次是动态的
除非知道签名的方式

**Comment by nianyuguai** [comment]
> 错误
> 🔔什么值得买, 开始!
> 
> ❗️什么值得买, 错误!
> TypeError: null is not an object (evaluating '_data.data.checkin_status')
> 
> ==============📣系统通知📣==============
> 什么值得买
> PC: 成功, APP: 0/1
> 累计: 12次, 经验: 2843, 金币: 3, 积分: 47
> 点击查看详情
> 
> anxx: 失败. undefined

最新App的登录请求已经修改了，APP端每次请求都要带sign参数，而且每次是动态的
除非知道签名的方式

**Comment by chavyleung** [comment]
Close: https://github.com/chavyleung/scripts/commit/5b8369d605be1b6996a9ff918287ecd4d3316972

更新[什么值得买]: 移除 APP 端签到 (原因: APP 端增加了参数校验)
