### ISSUE TITLE
quanx新用户，按文档操作报错，

### ISSUE THREAD

**Issue by leeween** [chavyleung/scripts#295]
# 安装路径: 
 ​ 风车 > 重写 > 引用

# BoxJs 稳定版

访问boxjs.com，日志提示
2021/01/29 21:47:53:797  <error>      [QTXDataParser] Skipped rewrite for http://boxjs.com/ with reason https://gitee.com/chavyleung/scripts/raw/master/chavy.box.js null script.

更新也无用

**Comment by chavyleung** [comment]
> 如果，你是 QuanX 的新用户（购买一周内）
> 点击风车 > 重写 > 引用 > 点击重写 > 更新 > 重启代理 (VPN)

试试单独更新一下 boxjs 的重写
