### ISSUE TITLE
萌新：按文档操作报错

### ISSUE THREAD

**Issue by 502880166** [chavyleung/scripts#304]
QuanX
# 安装路径: 
 ​ 风车 > 重写 > 引用
# BoxJs 稳定版
  https://gitee.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.quanx.conf

完全按照上述教程安装好后，提示：2021/02/04 18:01:35:570  <error>      [QTXDataParser] Skipped rewrite for http://boxjs.com/ with reason https://gitee.com/chavyleung/scripts/raw/master/chavy.box.js null script.

然后我单独更新BOXJS的重写和全部一起更新重写，反复刷新quanx都没有，还是提示上述错误，大佬请问是什么情况吖

**Comment by chavyleung** [comment]
就是没更新成功，试试开全局再单独更新

**Comment by chavyleung** [comment]
https://github.com/chavyleung/scripts/issues/295

**Comment by 502880166** [comment]
大佬是开的全局然后单独更新，但是他还是提示需要更新，并且重复这样，我程序重启过了手机也重新开机了，而且我确保我是能上谷歌这些网站的，点了更新还是显示需要更新

**Comment by shouyiyangwencong** [comment]
我也是这样的，怎么更新都不行。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 502880166 <notifications@github.com&gt;
发送时间: 2021年2月4日 18:58
收件人: chavyleung/scripts <scripts@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[chavyleung/scripts] 萌新：按文档操作报错 (#304)





 
大佬是开的全局然后单独更新，但是他还是提示需要更新，并且重复这样，我程序重启过了手机也重新开机了，而且我确保我是能上谷歌这些网站的，点了更新还是显示需要更新

**Comment by 502880166** [comment]
> 就是没更新成功，尽量开开再单独更新

大佬上面也有个和我一样的人= =   我也按照你说的做了还是没有用，还是显示需要更新   明明单独更新了还是显示需要更新

**Comment by chavyleung** [comment]
> > 就是没更新成功，尽量开开再单独更新
> 
> 大佬上面也有个和我一样的人= = 我也按照你说的做了还是没有用，还是显示需要更新 明明单独更新了还是显示需要更新

怎么更新的？把详细步骤讲一下

**Comment by 502880166** [comment]
> > > 就是没更新成功，尽量开开再单独更新
> > 
> > 
> > 大佬上面也有个和我一样的人= = 我也按照你说的做了还是没有用，还是显示需要更新 明明单独更新了还是显示需要更新
> 
> 怎么更新的？把详细步骤讲一下

 风车 > 重写 > 引用 > 点击已经添加的资源链接（boxjs的） > 点击更新 > 长按风车 > 左下角的刷新

**Comment by chavyleung** [comment]
> > > > 就是没更新成功，尽量开开再单独更新
> > > 
> > > 
> > > 大佬上面也有个和我一样的人= = 我也按照你说的做了还是没有用，还是显示需要更新 明明单独更新了还是显示需要更新
> > 
> > 
> > 怎么更新的？把详细步骤讲一下
> 
> 风车 > 重写 > 引用 > 点击已经添加的资源链接（boxjs的） > 点击更新 > 长按风车 > 左下角的刷新

反馈给 quanx 作者吧，这不是脚本层面能解决的问题了

**Comment by shouyiyangwencong** [comment]
我现在boxjs打开空白，请问是怎么回事？

**Comment by chavyleung** [comment]
急救

https://chavyleung.gitbook.io/boxjs/advanced/aid

**Comment by shouyiyangwencong** [comment]
这两个脚本我都操作了，还是空白。我之前只备份了一个备份。然后我是商店下载的圈X，刚刚打开测试版boxjs，boxjs版本居然更新了。然后订阅也都在。不知道这样有没有影响，我更新定阅，也都可以。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chavy <notifications@github.com&gt;
发送时间: 2021年2月5日 11:34
收件人: chavyleung/scripts <scripts@noreply.github.com&gt;
抄送: shouyiyangwencong <2530319054@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[chavyleung/scripts] 萌新：按文档操作报错 (#304)

**Comment by chavyleung** [comment]
执行急救脚本前，有没把 qx 的示例代码先删掉再粘贴

**Comment by shouyiyangwencong** [comment]
删掉了，就运行两行代码，log输出也是空白。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chavy <notifications@github.com&gt;
发送时间: 2021年2月5日 11:47
收件人: chavyleung/scripts <scripts@noreply.github.com&gt;
抄送: shouyiyangwencong <2530319054@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[chavyleung/scripts] 萌新：按文档操作报错 (#304)





 
执行急救脚本前，有没把 qx 的示例代码先删掉再粘贴

**Comment by shouyiyangwencong** [comment]
这是tf版boxjs,我的圈X是商店下载的。可以看到备份没有了，应该是脚本起作用了吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chavy <notifications@github.com&gt;
发送时间: 2021年2月5日 11:47
收件人: chavyleung/scripts <scripts@noreply.github.com&gt;
抄送: shouyiyangwencong <2530319054@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[chavyleung/scripts] 萌新：按文档操作报错 (#304)





 
执行急救脚本前，有没把 qx 的示例代码先删掉再粘贴

**Comment by hacken156026692** [comment]
打扰问下，大神，从别处看到qx的一个活动，人家艾特您感谢您的函数。

想确认一下，我在termux里运行node，失败。是否这些活动，只能在QX等iso平台运行。

node jd_entertainment.js

🔔百变大咖秀, 开始!
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './jdCookie.js'
Require stack:
- /data/data/com.termux/files/home/qx/jd_entertainment.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/qx/jd_entertainment.js:29:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/data/data/com.termux/files/home/qx/jd_entertainment.js' ]

**Comment by chavyleung** [comment]
Env

> 打扰问下，大神，从别处看到qx的一个活动，人家艾特您感谢您的函数。
> 
> 想确认一下，我在termux里运行node，失败。是否这些活动，只能在QX等iso平台运行。
> 
> node jd_entertainment.js
> 
> 🔔百变大咖秀, 开始!
> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module './jdCookie.js'
> Require stack:
> 
> * /data/data/com.termux/files/home/qx/jd_entertainment.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>   at Module.require (internal/modules/cjs/loader.js:952:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object. (/data/data/com.termux/files/home/qx/jd_entertainment.js:29:35)
>   at Module._compile (internal/modules/cjs/loader.js:1063:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>   at Module.load (internal/modules/cjs/loader.js:928:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/data/data/com.termux/files/home/qx/jd_entertainment.js' ]

Env.js 是可以运行在 NodeJs 环境的，但这个脚本的情况你应该咨询该脚本作者。
