### ISSUE TITLE
QX飞客茶馆能正常签到，但不显示通知

### ISSUE THREAD

**Issue by archyc** [chavyleung/scripts#307]
求大神更新。

**Comment by chavyleung** [comment]
fixed: https://github.com/chavyleung/scripts/commit/6b0b394f261e5431a5d87944a6689660c6a0d4be

**Comment by archyc** [comment]
大神，又出现了问题啦，定时签到就会出现这个错误日志，但是能成功签到。手动签到会出现通知，也没问题。

00:00:11.705518 
飞客茶馆, 开始!
00:00:12.493804 An exception was catched while evaluate script 飞客茶馆_签到: ReferenceError: Can't find variable: title. Line number 30, column: 18
00:00:12.493853 [Script Aborted]
----------------------------

**Comment by chavyleung** [comment]
更新后再试，有问题再 reopen
