### ISSUE TITLE
WPS只能邀请1个人了

### ISSUE THREAD

**Issue by flyer1229** [chavyleung/scripts#310]
WPS智能邀请一个人了，

**Comment by chavyleung** [comment]
是不是改成只邀 1 人就行？

**Comment by flyer1229** [comment]
是这个邀请的脚本之前可以邀请10-14个人的，现在这个脚本只能成功邀请一个人了。

**Comment by qingyunxin** [comment]
好像是wps开始限制了，把代码改成几秒邀请一个人应该就行了

**Comment by chavyleung** [comment]
fixed: https://github.com/chavyleung/scripts/commit/8f4e7a66d06d32ad74a468d1a8077725af60eeb5
