### ISSUE TITLE
新手想来问问Env.js的功能

### ISSUE THREAD

**Issue by Lkiku** [chavyleung/scripts#314]
最近想研究一下脚本，但不知道Env.js到底是干嘛的，看代码感觉像实现文件读取和发送请求啥的，但是也没看明白怎么用

**Comment by chavyleung** [comment]
EnvJs 是用来适匹多种运行环境的，通过调用 EnvJs 的接口写的脚本，可以做到一份代码同时运行在 Surge、QuanX、Loon、小火箭、NodeJs 环境下
