### ISSUE TITLE
什么值得买

### ISSUE THREAD

**Issue by TOTyangyang** [chavyleung/scripts#317]
总显示pc未登录，是要在哪儿登陆？

**Comment by chavyleung** [comment]
重取 ck 试试

**Comment by chavyleung** [comment]
有问题继续回复

**Comment by TOTyangyang** [comment]
谢谢，成功了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chavy ***@***.***&gt;
发送时间: 2021年3月10日 17:25
收件人: chavyleung/scripts ***@***.***&gt;
抄送: TOTyangyang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[chavyleung/scripts] 什么值得买 (#317)





 
有问题继续回复
