### ISSUE TITLE
飞客茶馆

### ISSUE THREAD

**Issue by WowYiJiu** [chavyleung/scripts#318]
连续几天定时运行出现长期活跃状态无法自动释放，app中显示是签到状态，再次执行可以提醒重复签到并释放

**Comment by archyc** [comment]
是不是也是这个错误提示？

00:00:11.705518
飞客茶馆, 开始!
00:00:12.493804 An exception was catched while evaluate script 飞客茶馆_签到: ReferenceError: Can't find variable: title. Line number 30, column: 18
00:00:12.493853 [Script Aborted]

**Comment by WowYiJiu** [comment]
> 是不是也是这个错误提示？
> 
> 00:00:11.705518
> 飞客茶馆, 开始!
> 00:00:12.493804 An exception was catched while evaluate script 飞客茶馆_签到: ReferenceError: Can't find variable: title. Line number 30, column: 18
> 00:00:12.493853 [Script Aborted]

我忘了，主要每次圈x遇到脚本执行记录里长期活跃的脚本我都会关闭圈叉重新开启，我的飞客茶馆也是在脚本执行记录里一直保持活跃

**Comment by chavyleung** [comment]
> 连续几天定时运行出现长期活跃状态无法自动释放，app中显示是签到状态，再次执行可以提醒重复签到并释放

我得先研究下什么情况会导致无法释放

**Comment by WowYiJiu** [comment]
> > 连续几天定时运行出现长期活跃状态无法自动释放，app中显示是签到状态，再次执行可以提醒重复签到并释放
> 
> 我得先研究下什么情况会导致无法释放

更新后签到正常了，或许之前是无法正常通知导致的
