### ISSUE TITLE
BoxJs - v0.7.75收藏应用上移下移没有反应

### ISSUE THREAD

**Issue by Catnipll** [chavyleung/scripts#321]
1️⃣loon Tf 2.1.9(268)
BoxJs - v0.7.75

点击收藏应用，上移、下移，没有任何反应，最顶部loon图标闪动一下后不会移动。

用的脚本地址：https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.loon.tf.plugin

2️⃣Quantumult X V1.0.19-build501
BoxJs - v0.7.75

点击收藏应用，上移、下移一切正常，即刻可移动。

用的脚本地址：https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.quanx.tf.conf

3️⃣求大佬修复

**Comment by chavyleung** [comment]
备份一下 Loon 的数据，再把 QX 的备份导入到 Loon 呢

**Comment by Catnipll** [comment]
> 备份一下 Loon 的数据，再把 QX 的备份导入到 Loon 呢

大佬您好~刚才尝试了一下，备份了 Loon 的数据，然后再把 QX 的备份导入到 Loon ，一切正常，可以正常移动。

然后将11 Pro Max上————loon Tf 2.1.9(268)——BoxJs - v0.7.75——里的数据备份，导入到备用机iPhone X——loon Tf 2.1.9(268)——BoxJs - v0.7.75——里面，依旧无法上下移动收藏应用，这证明是我loon的BoxJs设置哪里出问题了吗？可是就是正常设置、正常抓cookie，我实在想不到哪里的问题能让收藏应用无法上下移动。如果您需要的话我可以将11 Pro Max上————loon Tf 2.1.9(268)——BoxJs - v0.7.75——里的数据备份私发给您，麻烦您啦~

**Comment by chavyleung** [comment]
恢复一下 Loon 的数据，并把 BoxJs 升至 v0.7.76
进入 偏好设置，运行一下`抹掉：收藏应用`

刷新下页面后，进入 BoxJs 并重新收藏和排序看是否正常。

**Comment by Catnipll** [comment]
> 恢复一下 Loon 的数据，并把 BoxJs 升至 v0.7.76
> 进入 偏好设置，运行一下`抹掉：收藏应用`
> 
> 刷新下页面后，进入 BoxJs 并重新收藏和排序看是否正常。

十分的完美！已经正常！感谢大佬指点！您辛苦了！🙏🏻🙏🏻🙏🏻感恩🙏🏻
