### ISSUE TITLE
请添加学习强国的答题辅助

### ISSUE THREAD

**Issue by fisher-admin** [chavyleung/scripts#33]
学习强国软件中挂文章和视频时长及数量可能会被系统识别封号，但对于每日答题、挑战答题等内容，一方面有相关题库，另外只是提供qx来提示答案，操作由人工完成，没有任何风险而且需求较大，请大佬研究哈🙏

**Comment by leon-zhu** [comment]
> 学习强国软件中挂文章和视频时长及数量可能会被系统识别封号，但对于每日答题、挑战答题等内容，一方面有相关题库，另外只是提供qx来提示答案，操作由人工完成，没有任何风险而且需求较大，请大佬研究哈🙏

党员怎么能这样呢？2333

**Comment by 714683642** [comment]
群众莫名躺枪，要学习强国

**Comment by H1karuru** [comment]
是个人才
