### ISSUE TITLE
最新版boxjs，全局备份无法复制，麻烦一下大佬

### ISSUE THREAD

**Issue by rcfan1** [chavyleung/scripts#336]
环境：loon，昨天把boxjs从v0.7.75升级到了v0.7.90，全局备份完复制数据后，粘贴出来是个双引号，麻烦问一下大佬，这个怎么搞，之前正常的啊。
PS：这个备份索引是什么意思，是不是现在备份到了某处了，用索引就能找到？
![IMG_2343](https://user-images.githubusercontent.com/69945315/115166592-85a46d80-a0e6-11eb-9592-63b4dcd72991.PNG)
![IMG_2344](https://user-images.githubusercontent.com/69945315/115166596-8937f480-a0e6-11eb-8846-f95b91a20069.PNG)

**Comment by rcfan1** [comment]
顺便问一下，boxjs能否回退旧版本？

**Comment by chavyleung** [comment]
不能回退版本，复制不了应该是因为数据太大，备份不进去，看看是不是有玩中青，应该是 body 太大了，如果数据正常备份，通过索引值可以在数据查看器查询到

**Comment by rcfan1** [comment]
> 不能回退版本，复制不了应该是因为数据太大，备份不进去，看看是不是有玩中青，应该是 body 太大了，如果数据正常备份，通过索引值可以在数据查看器查询到

多谢大佬回复，这个没有中青，就十个软件的ck，应该很小的，按照大佬的思路，刚才通过索引值没查到数据，可能是备份失败导致的，我重新备份了几次，这次可以了，看来存在备份失败的问题啊（我有中青的那个手机也存在这个问题，我再去试试）。
再次表示感谢
