### ISSUE TITLE
boxjs之前没问题，突然就无法使用

### ISSUE THREAD

**Issue by JiYi12300** [chavyleung/scripts#355]
调试模式：$.web = xxxx
[ ERROR ] 调试模式：正在使用缓存的页面！
![](https://files.catbox.moe/wbbjh9.png)

**Comment by chavyleung** [comment]
侧栏里关掉调试

**Comment by chavyleung** [comment]
有问题再 Reopen

**Comment by JiYi12300** [comment]
完全进不去boxjs里面，所以关闭不了
可能是我qx设置的问题，之后卸载qx再来一遍就恢复正常了
