### ISSUE TITLE
ios“添加到主屏幕”后每次打开都卡死，浏览器内“ 127.0.0.1:9999”无问题

### ISSUE THREAD

**Issue by ee-5** [chavyleung/scripts#358]
使用的配置是
https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js, tag=BoxJS, path=^/, enabled=true
监听地址
0.0.0.0
端口
9999
地址
http://127.0.0.1:9999

桌面图标每次打开后点击一下，之后会卡死，
浏览器界面没问题。
版本是0.7.9

**Comment by chavyleung** [comment]
重新添加到主屏幕试试

**Comment by ee-5** [comment]
反复试了好几次，都是这个问题

**Comment by ee-5** [comment]
Emmm，重启ipad好了。。。非常感谢
