### ISSUE TITLE
求教 乱码有什么解决方法嘛

### ISSUE THREAD

**Issue by dukecd33369** [chavyleung/scripts#365]
返回的数据为GBK 默认解码为UTF-8 返回的data会是乱码有什么解决方法嘛
我使用了您的API   Env.min.js

**Comment by chavyleung** [comment]
暂时没有办法，这个貌似在脚本层面无法解决，可以发邮件咨询下 app 作者看，我也想知道有没解决方案

**Comment by dukecd33369** [comment]
我看到网上有个帖子 使用iconv-lite 来解决的
实际上我还是个初学者 您写的API Env.min.js 我并没看懂 您看用这个iconv-lite 能解决嘛
链接是https://blog.csdn.net/javajiawei/article/details/65935338

**Comment by dukecd33369** [comment]
我试着改了下您的API  Env.js 
在windows Node.js环境下 post方式 成功使用iconv-lite以GBK解码了返回的data
具体改动是在第322行 post函数中的第358行
//const { statusCode: status, statusCode, headers, body } = resp
//callback(null, { status, statusCode, headers, body }, body)
const { statusCode: status, statusCode, headers, rawBody } = resp
callback(null, { status, statusCode, headers, rawBody }, rawBody)
再使用iconv-lite以GBK解码rawBody 就是正常中文了

**Comment by dukecd33369** [comment]
还有一点就是 需要在opts.encoding = 'buffer'

**Comment by dukecd33369** [comment]
其他Surge Loon Qx 环境没有测试过

**Comment by chavyleung** [comment]
Close https://github.com/chavyleung/scripts/pull/367
