### ISSUE TITLE
求增加“联想社区APP”或者“联想社区web”签到

### ISSUE THREAD

**Issue by orangexw** [chavyleung/scripts#37]
希望增加联想社区签到，联想社区签到可以用天数换笔记本或者手机的保修期限，希望考虑增加一下。谢谢。

**Comment by orangexw** [comment]
希望有时间关注一下，谢谢啊！

**Comment by chavyleung** [comment]
@GideonSenku

**Comment by GideonSenku** [comment]
> 希望有时间关注一下，谢谢啊！
可以在tg上@GideonSenku或者@chavyleung

**Comment by chavyleung** [comment]
app估计搞不掂，有参数签名校验
得看看web有没办法

**Comment by orangexw** [comment]
> app估计搞不掂，有参数签名校验
> 得看看web有没办法

https://mclub.lenovo.com.cn/
移动版页面有签到模块

**Comment by JEGNUI** [comment]
大佬搞好了记得叫我一下
