### ISSUE TITLE
boxjs无法批量更新

### ISSUE THREAD

**Issue by yogayyy** [chavyleung/scripts#370]
请教一下大佬，boxjs无法批量更新，圈X有开始更新的通知但脚本显示object，单独一个个更新是可以的，surge的话有开始更新的通知但没有更新成功的通知，实际刷新下页面其实更新成功了部分，不知道什么原因。surge正常配置，圈x使用http backend。

**Comment by chavyleung** [comment]
应该是其中有一个或多个订阅不可访问了，导致批量更新中断
