### ISSUE TITLE
顺丰签到失败

### ISSUE THREAD

**Issue by WindStill** [chavyleung/scripts#387]
iOS 15.3 NE v1.0.27-build626 39.61MB

Logs:

🔔顺丰速运, 开始!
[object Object]
[object Object]

==============📣系统通知📣==============
顺丰速运
签到: 失败

每日任务: 
浏览积分商城页面达20s: 积分已领取
浏览会员权益达20s: 积分已领取
查询包裹进度: 积分已领取！

🔔顺丰速运, 结束! 🕛 5.316 秒

**Comment by chavyleung** [comment]
fix: https://github.com/chavyleung/scripts/commit/a6ead621b1bf8f80b0ba1a817c425cae2b99ddb3
