### ISSUE TITLE
提示 020/02/13 16:35:33:929  <error>      [QTXDataParser] Skipped rewrite for https://access.video.qq.com/user/auth_refresh?type=qq&g_tk=1950468863&vappid=11059694&vsecret=fdf61a6be0aad57132bc5cdf78ac30145b6cd2c1470b0cfe&_=1581582933902&callback=jsonp4 with reason videoqq.cookie.js null script.

### ISSUE THREAD

**Issue by yogoweili** [chavyleung/scripts#39]
020/02/13 16:35:33:929  <error>      [QTXDataParser] Skipped rewrite for https://access.video.qq.com/user/auth_refresh?type=qq&g_tk=1950468863&vappid=11059694&vsecret=fdf61a6be0aad57132bc5cdf78ac30145b6cd2c1470b0cfe&_=1581582933902&callback=jsonp4 with reason videoqq.cookie.js null script.

**Comment by chavyleung** [comment]
没找到videoqq.cookie.js这个脚本，
1. 看下是不是没放对地方
2. 或者下载的时候没有以raw形式来下载

**Comment by chavyleung** [comment]
先close，还有问题可继续回复本issues
