### ISSUE TITLE
喜马拉雅和叮咚买菜签到失败

### ISSUE THREAD

**Issue by KimShine007** [chavyleung/scripts#390]
叮咚买菜加载cookie成功，签到失败：

iPadOS 15.3.1 NE v1.0.27-build626 40.30MB

Logs:

🔔 叮咚买菜 开始签到
❌ 叮咚买菜 signapp - 签到失败: SyntaxError: JSON Parse error: Unrecognized token '<'
❌ 叮咚买菜 signapp - response: {"statusCode":405,"headers":{"X-Proxy":"lb1pre.psht3.mc.ops","Server":"nginx","Content-Type":"text/html; charset=utf-8","Content-Length":"157","Connection":"keep-alive","Date":"Wed, 09 Mar 2022 05:03:09 GMT"},"bodyBytes":{},"body":"<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx/1.16.0</center>\r\n</body>\r\n</html>\r\n"}
❌ 叮咚买菜 签到失败: TypeError: undefined is not an object (evaluating 'signinfo.signapp.code')

喜马拉雅l加载cookie没提示，不知道成功没，签到失败：

iPadOS 15.3.1 NE v1.0.27-build626 40.44MB

Logs:

🔔喜马拉雅, 开始!

==============📣系统通知📣==============
喜马拉雅
获取账号信息: 失败
说明: SyntaxError: JSON Parse error: Unexpected identifier "undefined"
❌ 喜马拉雅 getacc - 获取账号信息失败: SyntaxError: JSON Parse error: Unexpected identifier "undefined"
❌ 喜马拉雅 getacc - response: {"status":401,"statusCode":401,"headers":{"Content-Type":"application/json; charset=UTF-8","X-NWS-LOG-UUID":"16698323319763910389","x-a1-protocol-switch":"0","Server":"Tengine","X-Cache-Lookup":"Cache Miss","x-xlog-send":"false","x-sId":"174730291178511360","Date":"Wed, 09 Mar 2022 05:04:16 GMT","Content-Length":"0","Connection":"keep-alive","WS-TAG":"xmly","x-idc-gw":"sh-bs@adse$1#search$20#mobile$1"}}

❗️喜马拉雅, 错误!
TypeError: undefined is not an object (evaluating '$.signinfo.acc.data')

🔔喜马拉雅, 结束! 🕛 0.135 秒

麻烦大佬了，不是是我个例，还是脚本失效了。

**Comment by JoJoJotarou** [comment]
喜马拉雅cookie重写规则应该老旧了，你可手动添加一条重写规则，匹配的URL:`^https?:\/\/passport.ximalaya.com\/user-http-app\/v1\/token\/refresh`，其他不变，这个规则不好的一点就是每次进入app就会触发，切换app也会触发，所有获取cookie禁止需要禁止掉

**Comment by ooghost** [comment]
> 喜马拉雅cookie重写规则应该老旧了，你可手动添加一条重写规则，匹配的URL:`^https?:\/\/passport.ximalaya.com\/user-http-app\/v1\/token\/refresh`，其他不变，这个规则不好的一点就是每次进入app就会触发，切换app也会触发，所以获取cookie后需要禁止掉

手动添加的规则类型选哪个？

**Comment by JoJoJotarou** [comment]
> > 喜马拉雅cookie重写规则应该老旧了，你可手动添加一条重写规则，匹配的URL:`^https?:\/\/passport.ximalaya.com\/user-http-app\/v1\/token\/refresh`，其他不变，这个规则不好的一点就是每次进入app就会触发，切换app也会触发，所以获取cookie后需要禁止掉
> 
> 手动添加的规则类型选哪个？

类型：script-request-header 我刚刚试了下，必须开启HTTP数据抓取才行，估计是隐藏了请求

**Comment by GideonSenku** [comment]
https://t.me/NobyDa/447
