### ISSUE TITLE
BoxJs无法更新订阅呢。

### ISSUE THREAD

**Issue by z306334796** [chavyleung/scripts#398]

**Comment by z306334796** [comment]
就很奇怪，我配置了HTTP [Backend还是不能通过12.0.0.1:9999访问boxjs呢。而且我只用重写的话，竟然不能更新bosjs订阅呢。]
![photo_2022-05-11_11-03-23](https://user-images.githubusercontent.com/21018730/167760997-7401bb55-a8c1-4960-bbfd-4aed77422c02.jpg)
![photo_2022-05-11_11-03-23 (2)](https://user-images.githubusercontent.com/21018730/167761007-3a66a4d8-d4e5-46f0-b982-6a312e663e2a.jpg)
![photo_2022-05-11_11-03-24](https://user-images.githubusercontent.com/21018730/167761011-1ea9252c-2c87-4272-b835-c978f508ce46.jpg)

**Comment by chavyleung** [comment]
把主机名删掉

**Comment by z306334796** [comment]
> 把主机名删掉

我在bosjs偏好设置里将HTTP Backend Quan X部分改成了boxjs.com:9999可以正常访问和更新了，主机名是指127.0.01这个么？

**Comment by chavyleung** [comment]
<img width="636" alt="CleanShot 2022-05-11 at 11 15 08@2x" src="https://user-images.githubusercontent.com/29748519/167761983-1c92415f-205c-4c9e-bc2a-b64a3e2d1b37.png">

主机名指上面的 boxjs.com，因为你指定了主机名，所以你应该在 boxjs 里填 boxjs.com:9999
如果你不指定主机名，boxjs 里就看教程说的填 127.0.0.1:9999 即可

**Comment by z306334796** [comment]
> 

明白了，还是我理解错了，没有彻底理解这个概念呢。
