### ISSUE TITLE
2.1.18的loon上使用出现问题

### ISSUE THREAD

**Issue by PatrickScLau** [chavyleung/scripts#399]
日志显示这个问题，boxjs内添加的应用不工作
![E11D4C20-AC99-4560-8B8A-70A20F7672C4](https://user-images.githubusercontent.com/36791930/169439303-90b10039-a6fd-434e-befd-fe66c918875c.jpeg)
手动运行脚本显示
![93706C70-9E08-4CF5-95B2-EF89E23DC743](https://user-images.githubusercontent.com/36791930/169439480-39b646cf-3fe1-4d40-ba0a-cf4818deda6e.png)

**Comment by chavyleung** [comment]
正确安装 boxjs 插件后，用浏览器访问 [boxjs.com](http://boxjs.com) 即可。

**不要手动运行脚本**
**不要手动运行脚本**
**不要手动运行脚本**
