### ISSUE TITLE
大佬可否考虑写一个 虾米音乐 的签到脚本

### ISSUE THREAD

**Issue by JO2EY** [chavyleung/scripts#4]
大佬可否考虑写一个 虾米音乐 的签到脚本，感谢！

**Comment by chavyleung** [comment]
虾米音乐是怎么签到的？访问一下页面就可以了？

**Comment by JO2EY** [comment]
> 虾米音乐是怎么签到的？访问一下页面就可以了？

是的

**Comment by chavyleung** [comment]
据目前分析，虾米对参数做了比较严格的校验，这个恐怕实现不了

**Comment by chavyleung** [comment]
目前的思路都无法实现，后续有找到方法再跟进，先close。

**Comment by JO2EY** [comment]
大佬能否考虑支持下 饿了么 签到

**Comment by chavyleung** [comment]
饿了么签到不是有人写了吗？

**Comment by JO2EY** [comment]
> 饿了么签到不是有人写了吗？

是嘛 没有看到 能否分享下 = =

**Comment by chavyleung** [comment]
https://github.com/nzw9314/QuantumultX/commit/16aa2cf6d82d0afec13b9b94ed74ad04fe4adc92

**Comment by JO2EY** [comment]
感谢

**Comment by JO2EY** [comment]
这个貌似无法获取 cookies

**Comment by chavyleung** [comment]
应该可以的，昨天我看群上有人成功，你试试用189的写法或190的写法，都试试，或者到野比的群上问问

**Comment by JO2EY** [comment]
https://github.com/sazs34/TaskConfig/blob/master/all_in_one.js 谢谢 我在研究下 不过我用这个多合一的脚本是可以成功获取的
