### ISSUE TITLE
什么值得买不能签到了 请您看下

### ISSUE THREAD

**Issue by peirangg** [chavyleung/scripts#40]
2020/02/15 00:21:30:883  <console>    [JS Console]: 什么值得买, data: {"error_code":99,"error_msg":"\u8bf7\u5148\u767b\u5f55","data":[]}

**Comment by chavyleung** [comment]
`\u8bf7\u5148\u767b\u5f55`转换过来就是：请选登录
应该是cookie失效了，重新获取一下就好（cookie失效很正常，重新取就行）
重新取没问题后麻烦回来close issues
