### ISSUE TITLE
Mac + surge 无法执行脚本

### ISSUE THREAD

**Issue by ch634421335** [chavyleung/scripts#401]
macOS 使用surge安装boxjs的模块，可以正常访问boxjs.com，但是所有脚本执行显示"BoxJs"。请问是我配置有问题吗？还是macOS的问题。
macOS： 12.4 (21F79)
surge： 4.5.2（1663）

**Comment by chavyleung** [comment]
先在 surge 的配置文件中：[配置 HTTP-API](https://manual.nssurge.com/others/http-api.html)
再去 boxjs 中设置对应的 http-api 路径

**Comment by ch634421335** [comment]
> 先在 surge 的配置文件中：[配置 HTTP-API](https://manual.nssurge.com/others/http-api.html)
> 再去 boxjs 中设置对应的 http-api 路径

修改配置后执行示例代码可以正确输出。目前有个小bug，boxjs中修改 http-api 点击保存后下方不更新，仍然是examplekey。

**Comment by chavyleung** [comment]
看看是不是切换的问题，你在偏好设置中，可以以换行的方式配置多个 http-api 地址
然后在侧栏中，可以选择当前使用哪个 http-api （感觉你是没做这一步）

**Comment by ch634421335** [comment]
> 看看是不是切换的问题，你在偏好设置中，可以以换行的方式配置多个 http-api 地址
> 然后在侧栏中，可以选择当前使用哪个 http-api （感觉你是没做这一步）

侧边栏勾选上后再点保存下方就显示当前使用的 http-api 了，感谢帮助

**Comment by dissipator** [comment]
我刚开始在MAC OS 上使用surge和boxjs，不会配置，能给个教程，或截图之类的吗？

**Comment by chavyleung** [comment]
在 surge for mac 上安装 boxjs 的模块，然后在浏览器中访问 boxjs. com 即可
