### ISSUE TITLE
用很久了，突然出错（没升级ios16）

### ISSUE THREAD

**Issue by Abinthur** [chavyleung/scripts#402]
不知道为啥跳转总ww7.boxjs.com（和一些黄色网站？）
1.订阅很多
2.尝试使用过两个急救脚本均没用
3.相同配置下ipad一切正常，iPhone出的问题。

**Comment by chavyleung** [comment]
证明boxjs的重写没生效，没有安装boxjs订阅直接访问就是去到这个英文网站

自己检查下有没正确配置，启动模块，启用脚本（手误关掉了什么开关）

**Comment by chavyleung** [comment]
https://t.me/chavyscripts/253

**Comment by Abinthur** [comment]
应该是您说的原因，不过还是解决不了。我用的QX尝试

https://github.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.quanx.conf（一键）
和
https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.quanx.conf（手动）
都不行（ipad完全相同的配置可以…）话说这两个订阅地址有区别吗？
好神奇的bug。莫非是QX基础设置问题，导致不能调用脚本…

**Comment by Abinthur** [comment]
您刚才说的“启用模块和启用脚本”，是不是只要检查 复写里面的boxjs订阅 是勾选的还有其他可能遗漏的地方吗？

**Comment by Abinthur** [comment]
我暂时换用loon能正常用，不行就先这样吧～还想问两个非常小白的问题：
1.boxjs里的应用，是只要订阅就生效还是订阅后星标后才生效呀？
2.使用boxjs里的应用是不是只要在boxjs里操作，一般不用在qx应用里面再添加相关资源？（应用管理器还是应用配置管理器？）

**Comment by chavyleung** [comment]
![133F9177-7A9E-4426-B616-2A9426A0CC0D](https://user-images.githubusercontent.com/29748519/173215300-47d55b02-11ef-4568-a3a8-92083054bfbf.png)

确认这两个开关为打开状态

检查之前有没手动添加过boxjs订阅，如果有，先删除，避免重复添加，再检查之前有无添加 httpbackend，如果有，也删掉

1，添加boxjs订阅就可以用，星标是为了可以在首页显示图标方便进入

2，boxjs只是配置脚本运行时的参数，如cookie等，当然也可以以手动的方式运行脚本，但如果你想脚本每天定时运行，还是需要另外在qx中配置定时脚本任务

**Comment by Abinthur** [comment]
谢谢🙏
