### ISSUE TITLE
喜马拉雅签到脚本失效

### ISSUE THREAD

**Issue by KimShine007** [chavyleung/scripts#418]
cookie 可以正常写入，签到失败：

iOS 15.6.1 (19G82) NE v1.1.0-build767 42.48MB

Logs:

🔔喜马拉雅, 开始!

==============📣系统通知📣==============
喜马拉雅
获取账号信息: 失败
说明: SyntaxError: JSON Parse error: Unexpected identifier "A"
❌ 喜马拉雅 getacc - 获取账号信息失败: SyntaxError: JSON Parse error: Unexpected identifier "A"
❌ 喜马拉雅 getacc - response: {"status":404,"statusCode":404,"headers":{"Server":"Tengine","Connection":"keep-alive","Content-Length":"54","Content-Type":"text/plain; charset=UTF-8","PCDN_SWITCH":"on","Date":"Mon, 10 Oct 2022 08:31:06 GMT"},"body":"A client error occurred /starwar/task/listen/account: "}

❗️喜马拉雅, 错误!
TypeError: undefined is not an object (evaluating '$.signinfo.acc.data')

🔔喜马拉雅, 结束! 🕛 0.364 秒

设备：iPhone 7

**Comment by GideonSenku** [comment]
https://t.me/NobyDa/447
