### ISSUE TITLE
顺丰异常希望大佬修复一下（提示能获取会话，但是签到异常）

### ISSUE THREAD

**Issue by uniqueww** [chavyleung/scripts#419]
iOS 16.0.2 (20A380) NE v1.1.0-build767 40.17MB

Logs:

🔔顺丰速运, 开始!
SyntaxError: JSON Parse error: Unrecognized token '<'

❗️顺丰速运, 错误!
TypeError: undefined is not an object (evaluating '$.login.obj')

🔔顺丰速运, 结束! 🕛 1.545 秒

**Comment by chavyleung** [comment]
我这边正常，看看是不是 App 没更新到最新，然后试试：退出登录，重新登录，再取 Cookie 试试

**Comment by Monoxide0120** [comment]
我更新最新版之后也是这样，顺丰APP回退到9.43.0就正常了

**Comment by yrx2324** [comment]
一样异常

**Comment by chavyleung** [comment]
fix: https://github.com/chavyleung/scripts/commit/a6ead621b1bf8f80b0ba1a817c425cae2b99ddb3
