### ISSUE TITLE
顺丰速运运行异常

### ISSUE THREAD

**Issue by yrx2324** [chavyleung/scripts#421]
抓取回话运行后提示如下:
iOS 14.7.1 (18G82) NE v1.1.0-build767 6.03MB

Logs:

顺丰速运, 开始!

顺丰速运, 错误!
SyntaxError: JSON Parse error: Unrecognized token '<'

顺丰速运, 结束!  2.995 秒

卸载重装圈x,降级顺丰,更换网络都试过均无效,麻烦大佬帮忙看看

**Comment by chavyleung** [comment]
fix: https://github.com/chavyleung/scripts/commit/a6ead621b1bf8f80b0ba1a817c425cae2b99ddb3
