### ISSUE TITLE
联通签到超时退出，字幕组app签到显示未登录

### ISSUE THREAD

**Issue by Jessire** [chavyleung/scripts#43]

**Comment by chavyleung** [comment]
## 两个脚本的问题请分开issues

### 联通签到超时
1. 确保脚本更新到最新状态
2. 确保更新链接&Cookie都获取成功（获取成功后马上注释获取脚本，不要重复获取）
3. 如果你执行了上述步骤还有超时问题，请尝试手动修改下`10010.js`的代码，`get`改为`post`
```js
# 第 34 行, 把 get 改为 post 
chavy.get(url, (error, response, data) => {

# 修改为
chavy.post(url, (error, response, data) => {
```
### 字幕组签到
1. 字幕组app是需要单独从app中获取Cookie的（详见README）

**Comment by Jessire** [comment]
### 联通签到超时

1.联通签到脚本均为最新状态
2.更新链接&Cookie都获取成功
3.代码已修改，仍然有超时问题
QX日志显示 singapp:undefined

**Comment by chavyleung** [comment]
有条件的话，用thor抓包发我tg:  [@chavyleung](https://t.me/chavyleung)

杀联通, 开抓包, 开联通，签到，关抓包，导出har（选包含）。
