### ISSUE TITLE
bug： can not open boxjs.com

### ISSUE THREAD

**Issue by yunshuaipeng** [chavyleung/scripts#438]
https://user-images.githubusercontent.com/44765369/229766772-6ff1bd1c-49f2-4231-b974-3cedc9bdeeb1.MOV

**Comment by riverO0o** [comment]
我觉得安装说明写的有问题，一键安装感觉是骗小朋友的，明明装完还需要根据不同的app来检查各种开关有没有打开，而且现在很多人使用的都是托管的配置，修改根本不会生效。这些安装里面根本没提。
