### ISSUE TITLE
loon顺丰签到异常

### ISSUE THREAD

**Issue by Jessire** [chavyleung/scripts#450]
ck已获取，loon是商店最新版，下面是日志截图
![6208623866775976211_121](https://github.com/chavyleung/scripts/assets/61305123/7fa4f568-b3b5-4401-9c60-53f19e609881)

**Comment by liu296** [comment]
我也是这样

**Comment by Datou-cool** [comment]
关闭mitm over http/2之后再获取rookie试试

**Comment by liu296** [comment]
> 通过http/2关闭mitm之后再进行新秀尝试
不行

**Comment by Datou-cool** [comment]
> 通过http/2关闭mitm之后再进行新秀尝试
> 不行

开启之后获取的rookie有问题，你把这个关了获取下rookie.然后关闭获取rookie脚本在开http/2运行签到脚本

**Comment by Jessire** [comment]
> > 通过http/2关闭mitm之后再进行新秀尝试
> > 不行
> 
> 开启之后获取的rookie有问题，你把这个关了获取下rookie.然后关闭获取rookie脚本在开http/2运行签到脚本

still not work

**Comment by Datou-cool** [comment]
那就不知道了，我关了这个之后获取的rookie就可以运行签到脚本.开着http/2获取的脚本怎么都运行错误> > > 通过http/2关闭mitm之后再进行新秀尝试
> 
> > > 不行
> 
> > 
> 
> > 开启之后获取的rookie有问题，你把这个关了获取下rookie.然后关闭获取rookie脚本在开http/2运行签到脚本
> 
> 
> 
> still not work

**Comment by Datou-cool** [comment]
对了你那个包含body开了吗.没开的话按我之前说的再试一次> > > 通过http/2关闭mitm之后再进行新秀尝试
> 
> > > 不行
> 
> > 
> 
> > 开启之后获取的rookie有问题，你把这个关了获取下rookie.然后关闭获取rookie脚本在开http/2运行签到脚本
> 
> 
> 
> still not work

**Comment by Datou-cool** [comment]
还有你看看脚本类型是不是http-request> > > 通过http/2关闭mitm之后再进行新秀尝试
> 
> > > 不行
> 
> > 
> 
> > 开启之后获取的rookie有问题，你把这个关了获取下rookie.然后关闭获取rookie脚本在开http/2运行签到脚本
> 
> 
> 
> still not work

**Comment by Datou-cool** [comment]
还有记得mitm这个（ccsp-egmas.sf-express.com）> > > 通过http/2关闭mitm之后再进行新秀尝试
> 
> > > 不行
> 
> > 
> 
> > 开启之后获取的rookie有问题，你把这个关了获取下rookie.然后关闭获取rookie脚本在开http/2运行签到脚本
> 
> 
> 
> still not work

**Comment by Jessire** [comment]
![F393970D-2C0C-4A61-AE60-3827145F3D14](https://github.com/chavyleung/scripts/assets/61305123/7d4af1e8-2c4c-4607-8ad8-333a841c078f)

**Comment by Jessire** [comment]
提示ck获取成功，mitm也关了

**Comment by Jessire** [comment]
![2095858D-E766-4D42-A4F8-208112FA0B72](https://github.com/chavyleung/scripts/assets/61305123/d1c339ca-a4ff-4536-b979-beb32b8b02a0)

看看ck有问题不

**Comment by Jessire** [comment]
可以了，多获取几次

**Comment by chavyleung** [comment]
> 可以了，多获取几次

还有这种操作？🤨

**Comment by liu296** [comment]
圈x能用吗

**Comment by liu296** [comment]
> 还有你看看脚本类型是不是http-request> > > 通过http/2关闭mitm之后再进行新秀尝试
> 
> > > > 不行
> > 
> > 
> > > 
> > 
> > 
> > > 开启之后获取的rookie有问题，你把这个关了获取下rookie.然后关闭获取rookie脚本在开http/2运行签到脚本
> > 
> > 
> > still not work
[哥你真棒，我的圈x和loon都搞定了
![image](https://github.com/chavyleung/scripts/assets/101170632/a82a6e76-86be-42b7-8b38-129b87a4627f)

![image](https://github.com/chavyleung/scripts/assets/101170632/ab2bad1d-0784-4b03-9f2b-3468b26bf18d)
