### ISSUE TITLE
备份出错

### ISSUE THREAD

**Issue by qhy5697062** [chavyleung/scripts#454]
新版本v0.12.11使用旧版v.0.12.10的备份文件恢复备份后，无法重新再备份

**Comment by qhy5697062** [comment]
换回旧版v.0.12.10成功备份

**Comment by chavyleung** [comment]
v.0.12.11 确实存在该问题，要查下什么原因

**Comment by chavyleung** [comment]
fix: https://github.com/chavyleung/scripts/releases/tag/0.12.12
