### ISSUE TITLE
贴吧签到 need vcode

### ISSUE THREAD

**Issue by cristinarccc** [chavyleung/scripts#46]
贴吧签到100个吧后 无法继续签到，日志显示need vcode 编码2150040，请问这种情况怎么解决呢，重新登陆获取cookie不奏效

**Comment by chavyleung** [comment]
每天都是这几个吧吗？
手动重签能解决不？
吧名是什么，确认下这吧是否还存在

**Comment by cristinarccc** [comment]
每天都是这几个吧，手动签到后第二天还是不行

- 
"iphonexs"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:02:843  <console>    [JS Console]: [百度贴吧] "telegram"签到结果: 失败, 编码: 1010, 原因: 贴吧目录出问题啦，请到贴吧签到吧反馈
2020/02/23 10:15:02:916  <console>    [JS Console]: [百度贴吧] "手机壁纸"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:03:020  <console>    [JS Console]: [百度贴吧] "动漫壁纸"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:03:181  <console>    [JS Console]: [百度贴吧] "辉夜大小姐想让我告白"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:03:210  <console>    [JS Console]: [百度贴吧] "星期一的丰满"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:03:384  <console>    [JS Console]: [百度贴吧] "为美好的世界献上祝福"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:03:385  <console>    [JS Console]: [百度贴吧] "擅长捉弄的高木同学"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:03:555  <console>    [JS Console]: [百度贴吧] "亲吻姐姐"签到结果: 失败, 编码: 1010, 原因: 贴吧目录出问题啦，请到贴吧签到吧反馈
2020/02/23 10:15:03:584  <console>    [JS Console]: [百度贴吧] "青春期笨蛋不做兔女郎学姐的梦"签到结果: 失败, 编码: 2150040, 原因: need vcode
2020/02/23 10:15:03:594  <console>    [JS Console]: 百度贴吧, 签到结果: 部分成功, 今日共签: 100/121, 本次成功: 0, 本次失败: 21
2020/02/23 10:15:03:909  <console>    [JS Console]: [百度知道] 签到结果: 成功, {"errorNo":0,"data":

**Comment by chavyleung** [comment]
像tg，亲吻姐姐这种吧，不用看都是肯定是不存在的了

其他没被封禁的吧应该是可以通过手动签到的方式签到的吧？
每天自动几次也签不上吗？

**Comment by cristinarccc** [comment]
是的，除了这些被封禁的吧，其它都是可以手动签到，我今天签了5次都失败

**Comment by chavyleung** [comment]
尝试下在关注的吧里清除掉这些被封禁的吧，理论上手动签到能签上的自动签到肯定子是能签的

**Comment by chavyleung** [comment]
你说的手动签到是指手动用脚本来签到，还是手动到贴吧app去签到？

**Comment by cristinarccc** [comment]
后者...我自己到app签可以签，在quanx调试里构造请求的话也还是签到不了，封禁吧已经清除了

**Comment by chavyleung** [comment]
回头我关注这些吧测试下

**Comment by MisterGlasses** [comment]
我一块10个吧 偶尔也会这样 重签又没问题了

**Comment by chavyleung** [comment]
need vcode 是因为签过频繁，贴吧要求输入图片验证码，重签或加入签到间隔时间可解
