### ISSUE TITLE
百度贴吧签到失败。

### ISSUE THREAD

**Issue by abxyap** [chavyleung/scripts#48]
2020/02/24 19:19:46:300  <console>    [JS Console]: [百度贴吧] "大学"签到结果: 失败, 编码: 2150040, 原因: need vcode

试了重新获取cookie也是一样。

**Comment by chavyleung** [comment]
过10分钟再签应该能签上

**Comment by abxyap** [comment]
这个是有什么原因吗？

**Comment by chavyleung** [comment]
就是不能一下次签太多，贴吧有限制，过一会就让你签了

**Comment by abxyap** [comment]
好的，谢谢。
