### ISSUE TITLE
大佬可否加一个APK.tw的签到吗？

### ISSUE THREAD

**Issue by androidcn** [chavyleung/scripts#5]
大佬可否加一个APK.tw的签到吗？

**Comment by androidcn** [comment]
常到这 下载 无损签到能拿积分免费下载
 https://apk.tw/forum-954-1.html

**Comment by chavyleung** [comment]
有空再看看能不能实现

**Comment by androidcn** [comment]
谢谢，这tw 必须fq访问

**Comment by chavyleung** [comment]
Surge&QuanX都无法在script里访问被墙网站，据刘大爷说这是ios的限制。
我在mac上测试通过了，是个半成品，因为ios无法用我就不上传的仓库，如果你需要给邮箱我单独发你

**Comment by androidcn** [comment]
路由翻，就没这个问题了吧，希望能加上！谢谢

**Comment by chavyleung** [comment]
https://github.com/chavyleung/scripts/tree/master/apktw

测试吧，有问题请new issues

**Comment by androidcn** [comment]
感谢

**Comment by androidcn** [comment]
OK，明天再测试一下

**Comment by androidcn** [comment]
手动-首次支持脚本 不提示
手动-再运行 显示 重复签到

**Comment by chavyleung** [comment]
日志看下有没报错

**Comment by sir8713642** [comment]
請問一下這要如何使用
