### ISSUE TITLE
BoxJS网页通过Alook打开空白

### ISSUE THREAD

**Issue by QianmuZ** [chavyleung/scripts#504]
surge模块安装，通过boxjs.com访问。
Alook页面打开空白，safari浏览器可以正常打开。
不清楚是boxjs的问题还是alook的问题

**Comment by chavyleung** [comment]
是不是 Alook 把 boxjs.com 列为广告给屏蔽掉了，试试 boxjs.net 或者看看 Alook 有没相关的白名单设置

**Comment by QianmuZ** [comment]
> 是不是 Alook 把 [boxjs.com](http://boxjs.com) 列为广告给屏蔽掉了，试试 [boxjs.net](http://boxjs.net) 或者看看 Alook 有没相关的白名单设置

确实👍，应该是alook或者嗒自带的规则屏蔽的
