### ISSUE TITLE
招商银行掌上生活

### ISSUE THREAD

**Issue by jiihsu** [chavyleung/scripts#54]
大啦可以帮忙弄个掌上生活的签到嘛，谢谢大佬。

**Comment by chavyleung** [comment]
招商不是有大佬弄了吗？cookie一天失效

**Comment by jiihsu** [comment]
了解了之前一段很早看到以为成功了😌，那只能手动签到了😞，谢谢大佬啊。
在 2020年3月6日 +0800 PM10:00，Chavy <notifications@github.com>，写道：
