### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by shunichio** [chavyleung/scripts#6]
由于Quantumult X目前不支持远程js脚本，但是，一个一个的下载脚本也很麻烦。。不知道大佬是否能够写一份利用working copy拷贝的配置文件，具体的可以参考下野比大佬的写法：https://github.com/NobyDa/Script/blob/master/QuantumultX/Js_local_WorkingCopy.conf

**Comment by chavyleung** [comment]
有空研究下，没玩过working copy

**Comment by shunichio** [comment]
好的。。大佬能够研究下IT之家的自动签到吗，想要。。哈哈。。要是能够支付自动签到获取积分就更好了。。❤😂😜

**Comment by chavyleung** [comment]
https://github.com/chavyleung/scripts/tree/master/sample

写了份示例配置，如果用`working copy` fetch到`Scripts/chavy`目录, 即可直接复制示例配置使用
注意了，这份示例配置只是方便复制配置用的，是不能直接远程引用或本地引用的。

IT之家随缘弄吧，issues最好分开提，不要混在一个issues里，以后不好索引，先Close
