### ISSUE TITLE
起点读书签到

### ISSUE THREAD

**Issue by mw418** [chavyleung/scripts#61]
大佬。跪求这个

**Comment by GideonSenku** [comment]
请保持项目的跟进,目前已在准备

**Comment by GideonSenku** [comment]
> 大佬。跪求这个

签到使用了RSA加密算法,有签名校验,无法实现了

**Comment by mw418** [comment]
好吧。感谢大佬的付出

**Comment by mw418** [comment]
> > 大佬。跪求这个
> 
> 签到使用了RSA加密算法,有签名校验,无法实现了

好的。感谢大佬的付出
