### ISSUE TITLE
[问题]使用“喜马拉雅HD”无法获取Cookie问题

### ISSUE THREAD

**Issue by Mornwind** [chavyleung/scripts#7]
使用场景：
- iPad Pro 11寸
- iPadOS 13.3
- Surge 4

问题描述：
使用“喜马拉雅HD“App，脚本无法获取Cookie。
但是通过“喜马拉雅”App能正常进行获取。

**Comment by chavyleung** [comment]
把日志贴一下

**Comment by chavyleung** [comment]
获取Cookie的正则有改过，确认下是不是使用最新的正则来取Cookie
https://github.com/chavyleung/scripts/commit/6196d04186c380879d153d42dcba16f59c2a0cb9

**Comment by Mornwind** [comment]
> 获取Cookie的正则有改过，确认下是不是使用最新的正则来取Cookie
> [6196d04](https://github.com/chavyleung/scripts/commit/6196d04186c380879d153d42dcba16f59c2a0cb9)

我确定使用的是最新的正则。我还录了个屏。

**Comment by chavyleung** [comment]
ok，回头我拿ipad测试下

**Comment by Mornwind** [comment]
> ok，回头我拿ipad测试下

我的录屏在这，有空您可以查看下：
http://sendanywhe.re/23YRQHC3
