### ISSUE TITLE
淘宝淘金币和领红包签到~

### ISSUE THREAD

**Issue by lcandy2** [chavyleung/scripts#72]
这个就稍微有点用啦，有时间的话建议先写这个quq

**Comment by GideonSenku** [comment]
> 这个就稍微有点用啦，有时间的话建议先写这个quq

阿里系列是有生之年系列,等不到的

**Comment by huangzhong123521** [comment]
> 这个就稍微有点用啦，有时间的话建议先写这个quq

**Comment by GideonSenku** [comment]
> > 这个就稍微有点用啦，有时间的话建议先写这个quq

能力不足危险
