### ISSUE TITLE
网易考拉签到失效

### ISSUE THREAD

**Issue by JKamiy** [chavyleung/scripts#75]
会提示：签到成功（重复），但实际未签到。
Surge4.0 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by GideonSenku** [comment]
> 会提示：签到成功（重复），但实际未签到。
> Surge4.0
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

已知问题,网易考拉Cookie存活时间低
