### ISSUE TITLE
巴哈姆特签到~

### ISSUE THREAD

**Issue by lcandy2** [chavyleung/scripts#77]
这个会很简单，不需要写太多，他的签到流程是打开app/访问网页自动签到
这个很有用，因为账号一定时间不登录会被删除...
有时间先写写这个吧

**Comment by JoJoJotarou** [comment]
NobyDa已经实现了[Bahamut签到脚本](https://github.com/NobyDa/Script/tree/master/Bahamut)请自行查看脚本注释了解使用方法，也可以直接订阅该地址：`https://raw.githubusercontent.com/NobyDa/Script/master/NobyDa_BoxJs.json`

希望是你想要的~😁
