### ISSUE TITLE
[请求]希望以后能加入“QQ会员”、“米游社（各社区独立签到）”的自动签到脚本

### ISSUE THREAD

**Issue by Mornwind** [chavyleung/scripts#8]
描述：
1. QQ会员成长值签到；
![image](https://user-images.githubusercontent.com/38060040/72160165-d7951880-33f8-11ea-95ad-4271388b864c.png)

1. 米游社（大别野/崩坏学园2/崩坏3/原神/未定事件簿）每日签到（各社区均为独立签到）。
![image](https://user-images.githubusercontent.com/38060040/72160433-4bcfbc00-33f9-11ea-8129-73f6785239ea.png)

**Comment by chavyleung** [comment]
最近比较忙，有空抓抓看

**Comment by xcj0422** [comment]
同希望

**Comment by Mornwind** [comment]
> 同希望

米游社的签到脚本，Chavy大佬已经写出来了。
QQ会员的签到，以及把抓包记录发过去了，Chavy大佬还在研究。
