### ISSUE TITLE
“小豆苗”app签到

### ISSUE THREAD

**Issue by lin768474155** [chavyleung/scripts#80]
签到送豆豆，可以换支付宝现金红包，各种实物

**Comment by GideonSenku** [comment]
> 签到送豆豆，可以换支付宝现金红包，各种实物

阿里系列默认放弃

**Comment by chavyleung** [comment]
> > 签到送豆豆，可以换支付宝现金红包，各种实物
> 
> 阿里系列默认放弃

这个应该不是阿里系

**Comment by chavyleung** [comment]
有校验，不能实现
