### ISSUE TITLE
请求增加IT之家签到脚本，万分感谢。

### ISSUE THREAD

**Issue by shunichio** [chavyleung/scripts#9]

**Comment by chavyleung** [comment]
简单抓了下包，不简单，有空再确认下能不能搞

**Comment by asnfohsdgfbkxcv** [comment]
战略性关注   刚需了

**Comment by MapleSpirit** [comment]
同关注一下

**Comment by Grergo** [comment]
新签到API 是 https://my.ruanmei.com/api/usersign/sign?userHash=[USERHASh]&type=signType&endt=[endt]
USERHASH 可以通过一次访问获取，endt可以通过以下方式获取：
将签到时的时间(yyyy-MM-dd\x20HH:mm:ss) 以**3DES**加密方式加密，模式是**ECB**，填充方式是**ZeroPadding**，加密密码是‘**HCa%Y|7#**’(不包含引号)

希望能够实现一下，谢谢！

**Comment by GideonSenku** [comment]
> 新签到API 是 https://my.ruanmei.com/api/usersign/sign?userHash=[USERHASh]&type=signType&endt=[endt]
> 
> USERHASH 可以通过一次访问获取，endt可以通过以下方式获取：
> 
> 将签到时的时间(yyyy-MM-dd\x20HH:mm:ss) 以**3DES**加密方式加密，模式是**ECB**，填充方式是**ZeroPadding**，加密密码是‘**HCa%Y|7#**’(不包含引号)
> 
> 
> 
> 希望能够实现一下，谢谢！

大佬🐂🍺

**Comment by Grergo** [comment]
麻烦更新下，新签到API如下：
https://my.ruanmei.com/api/usersign/sign?userHash=[**UserHash**]&type=0&timestamp=[**13位时间戳**]&[**gnekk()**]=[**geKsk()**]
gnekk与geKsK函数如下：(我用Python写了一下)
```
def gnekk():
    jsstr = get_js()
    ctx = execjs.compile(jsstr)
    #3DES加密 text:gekk(3),key:gekk(8) 模式：ECB 填充：ZeroPadding
    base=ctx.call('enc',gekk(3),gekk(8))
    #3DES加密结束
    text='k'+base64.b64decode(base).hex()
    return text
def geKsk():
    jsstr = get_js()
    ctx = execjs.compile(jsstr)
    # 3DES加密： text：签到时的时间(yyyy-MM-dd\x20HH:mm:ss) key：gekk（8） 模式：ECB 填充：ZeroPadding
    base = ctx.call('enc', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),gekk(8))
    # 3DES加密结束
    return base64.b64decode(base).hex()
def gekk(S):
    Skey="hd7%b4f8p9)*fd4h5l6|)123/*-+!#$@%^*()_+?>?njidfds[]rfbcvnb3rz/ird|opqqyh487874515/%90hggigadfihklhkopjj`b3hsdfdsf84215456fi15451%q(#@Fzd795hn^Ccl$vK^L%#w$^yr%ETvX#0TaPSRm5)OeG)^fQnn6^%^UTtJI#3EZ@p6^Rf$^!O$(jnkOiBjn3#inhOQQ!aTX8R)9O%#o3zCVxo3tLyVorwYwA^$%^b9Yy$opSEAOOlFBsS^5d^HoF%tJ$dx%3)^q^c^$al%b4I)QHq^#^AlcK^KZFYf81#bL$n@$%j^H(%m^"
    timeStemp=int(time.time()*1000)
    today=datetime.date.today().day
    Value1=round(timeStemp/50000)*today*3
    if S==3:
        return Skey[int(Value1%10000/1000)*today]+Skey[int(Value1%1000/100)*today]+Skey[int(Value1%100/10)*today]
    elif S==8:
        return Skey[int(Value1%100000000 / 10000000)*today]+Skey[int(Value1%10000000 / 1000000)*today]+Skey[int(Value1%1000000 / 100000)*today]+Skey[int(Value1%100000 / 10000)*today]+Skey[int(Value1%10000 / 1000)*today]+Skey[int(Value1%1000 / 100)*today]+Skey[int(Value1%100 / 10)*today]+Skey[int(Value1%10)*today]
```

**Comment by woshilijunhao** [comment]
> 麻烦更新下，新签到API如下：
> [https://my.ruanmei.com/api/usersign/sign?userHash=[**UserHash**]&type=0&timestamp=[**13位时间戳**]&[**gnekk()**]=[**geKsk()**]](https://my.ruanmei.com/api/usersign/sign?userHash=%5B**UserHash**%5D&type=0&timestamp=%5B**13%E4%BD%8D%E6%97%B6%E9%97%B4%E6%88%B3**%5D&%5B**gnekk()**%5D=%5B**geKsk()**%5D)
> gnekk与geKsK函数如下：(我用Python写了一下)
> 
> ```
> def gnekk():
>     jsstr = get_js()
>     ctx = execjs.compile(jsstr)
>     #3DES加密 text:gekk(3),key:gekk(8) 模式：ECB 填充：ZeroPadding
>     base=ctx.call('enc',gekk(3),gekk(8))
>     #3DES加密结束
>     text='k'+base64.b64decode(base).hex()
>     return text
> def geKsk():
>     jsstr = get_js()
>     ctx = execjs.compile(jsstr)
>     # 3DES加密： text：签到时的时间(yyyy-MM-dd\x20HH:mm:ss) key：gekk（8） 模式：ECB 填充：ZeroPadding
>     base = ctx.call('enc', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),gekk(8))
>     # 3DES加密结束
>     return base64.b64decode(base).hex()
> def gekk(S):
>     Skey="hd7%b4f8p9)*fd4h5l6|)123/*-+!#$@%^*()_+?>?njidfds[]rfbcvnb3rz/ird|opqqyh487874515/%90hggigadfihklhkopjj`b3hsdfdsf84215456fi15451%q(#@Fzd795hn^Ccl$vK^L%#w$^yr%ETvX#0TaPSRm5)OeG)^fQnn6^%^UTtJI#3EZ@p6^Rf$^!O$(jnkOiBjn3#inhOQQ!aTX8R)9O%#o3zCVxo3tLyVorwYwA^$%^b9Yy$opSEAOOlFBsS^5d^HoF%tJ$dx%3)^q^c^$al%b4I)QHq^#^AlcK^KZFYf81#bL$n@$%j^H(%m^"
>     timeStemp=int(time.time()*1000)
>     today=datetime.date.today().day
>     Value1=round(timeStemp/50000)*today*3
>     if S==3:
>         return Skey[int(Value1%10000/1000)*today]+Skey[int(Value1%1000/100)*today]+Skey[int(Value1%100/10)*today]
>     elif S==8:
>         return Skey[int(Value1%100000000 / 10000000)*today]+Skey[int(Value1%10000000 / 1000000)*today]+Skey[int(Value1%1000000 / 100000)*today]+Skey[int(Value1%100000 / 10000)*today]+Skey[int(Value1%10000 / 1000)*today]+Skey[int(Value1%1000 / 100)*today]+Skey[int(Value1%100 / 10)*today]+Skey[int(Value1%10)*today]
> ```

我自己记录了一些加密的方式，最后有个日历登录的，希望用的上：https://www.fxxkcar.com/blog/?p=166
我做了一个页面，帮助一些不会代码的完成自动签到：https://www.fxxkcar.com/ithome.html
希望老哥加个Q，这样以后之家改加密方式了，方便第一时间沟通（白嫖）

**Comment by GideonSenku** [comment]
> > 麻烦更新下，新签到API如下：
> > [https://my.ruanmei.com/api/usersign/sign?userHash=[**UserHash**]&type=0&timestamp=[**13位时间戳**]&[**gnekk()**]=[**geKsk()**]](https://my.ruanmei.com/api/usersign/sign?userHash=%5B**UserHash**%5D&type=0&timestamp=%5B**13%E4%BD%8D%E6%97%B6%E9%97%B4%E6%88%B3**%5D&%5B**gnekk()**%5D=%5B**geKsk()**%5D)
> > gnekk与geKsK函数如下：(我用Python写了一下)
> > ```
> > def gnekk():
> >     jsstr = get_js()
> >     ctx = execjs.compile(jsstr)
> >     #3DES加密 text:gekk(3),key:gekk(8) 模式：ECB 填充：ZeroPadding
> >     base=ctx.call('enc',gekk(3),gekk(8))
> >     #3DES加密结束
> >     text='k'+base64.b64decode(base).hex()
> >     return text
> > def geKsk():
> >     jsstr = get_js()
> >     ctx = execjs.compile(jsstr)
> >     # 3DES加密： text：签到时的时间(yyyy-MM-dd\x20HH:mm:ss) key：gekk（8） 模式：ECB 填充：ZeroPadding
> >     base = ctx.call('enc', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),gekk(8))
> >     # 3DES加密结束
> >     return base64.b64decode(base).hex()
> > def gekk(S):
> >     Skey="hd7%b4f8p9)*fd4h5l6|)123/*-+!#$@%^*()_+?>?njidfds[]rfbcvnb3rz/ird|opqqyh487874515/%90hggigadfihklhkopjj`b3hsdfdsf84215456fi15451%q(#@Fzd795hn^Ccl$vK^L%#w$^yr%ETvX#0TaPSRm5)OeG)^fQnn6^%^UTtJI#3EZ@p6^Rf$^!O$(jnkOiBjn3#inhOQQ!aTX8R)9O%#o3zCVxo3tLyVorwYwA^$%^b9Yy$opSEAOOlFBsS^5d^HoF%tJ$dx%3)^q^c^$al%b4I)QHq^#^AlcK^KZFYf81#bL$n@$%j^H(%m^"
> >     timeStemp=int(time.time()*1000)
> >     today=datetime.date.today().day
> >     Value1=round(timeStemp/50000)*today*3
> >     if S==3:
> >         return Skey[int(Value1%10000/1000)*today]+Skey[int(Value1%1000/100)*today]+Skey[int(Value1%100/10)*today]
> >     elif S==8:
> >         return Skey[int(Value1%100000000 / 10000000)*today]+Skey[int(Value1%10000000 / 1000000)*today]+Skey[int(Value1%1000000 / 100000)*today]+Skey[int(Value1%100000 / 10000)*today]+Skey[int(Value1%10000 / 1000)*today]+Skey[int(Value1%1000 / 100)*today]+Skey[int(Value1%100 / 10)*today]+Skey[int(Value1%10)*today]
> > ```
> 
> 我自己记录了一些加密的方式，最后有个日历登录的，希望用的上：https://www.fxxkcar.com/blog/?p=166
> 我做了一个页面，帮助一些不会代码的完成自动签到：https://www.fxxkcar.com/ithome.html
> 希望老哥加个Q120300443，这样以后之家改加密方式了，方便第一时间沟通（白嫖）

开学了没啥时间，有空看看吧

**Comment by lowking** [comment]
> 新签到API 是 https://my.ruanmei.com/api/usersign/sign?userHash=[USERHASh]&type=signType&endt=[endt]
> 
> USERHASH 可以通过一次访问获取，endt可以通过以下方式获取：
> 
> 将签到时的时间(yyyy-MM-dd\x20HH:mm:ss) 以**3DES**加密方式加密，模式是**ECB**，填充方式是**ZeroPadding**，加密密码是‘**HCa%Y|7#**’(不包含引号)
> 
> 
> 
> 希望能够实现一下，谢谢！

这都出来了，应该快了
