### ISSUE TITLE
网易云签到打卡+听歌数

### ISSUE THREAD

**Issue by lxyok** [chavyleung/scripts#91]
吾爱破解论坛有人发了一个帖子  https://www.52pojie.cn/thread-1131583-1-1.html

搭建了这个网站可以用来打卡 增加听歌数（每天三百）https://163.newlover.cn/
希望老哥 增加对这个网站的支持 签到的同时把 听歌数也刷满，谢谢了

登录 https://163.newlover.cn/api.php?do=login
签到 https://163.newlover.cn/api.php?do=sign
打卡增加听歌书 https://163.newlover.cn/api.php?do=daka

**Comment by lxyok** [comment]
这个是搭建打卡签到网站的源码 https://www.52pojie.cn/thread-1131545-1-1.html 
源码： https://www.lanzous.com/ia9enab

**Comment by nccuiki** [comment]
听歌数捷径就可以了

**Comment by WyattIsaac** [comment]
请问楼上的听歌数捷径可以自动运行吗？就是添加自动化之后还是需要点击确认，可以让他直接在后台自动运行而不需要确定的方法吗，请指教
