### ISSUE TITLE
顺丰 27 周年签到增加微信小程序实现签到

### ISSUE THREAD

**Issue by breakings** [chavyleung/scripts#96]
微信小程序正则和 App 有一点点区别，需要改动 cookies 和复写正则。
具体如下：
https://mcs-mimp-web.sf-express.com/mcs-mimp/share/weChat/shareGiftReceiveRedirect?source=xxxxxx
所以正则改动一下就可以实现小程序签到。
`^https:\/\/mcs-mimp-web.sf-express.com\/mcs-mimp\/share\/(*.?)\/share(*.?)Redirect url script-request-header sfexpress.cookie.js`

cookies 代码第 14 行也需要修改：

`} else if ($request && $request.method != 'OPTIONS' && $request.url.match(/mcs-mimp\/share\/(.*?)\/share(.*?)Redirect/)) {`

**Comment by chavyleung** [comment]
https://github.com/chavyleung/scripts/commit/dcaf763aa2299b2d30170d12211b8b73c89af7c9

感谢反馈
