### ISSUE TITLE
掌上飞车签到

### ISSUE THREAD

**Issue by horryruo** [chavyleung/scripts#99]
不知道有没有人有需求，大佬能做一个嘛，我抓了个包

**Comment by GideonSenku** [comment]
> 不知道有没有人有需求，大佬能做一个嘛，我抓了个包

可以重放吗？

**Comment by horryruo** [comment]
> > 不知道有没有人有需求，大佬能做一个嘛，我抓了个包
> 
> 可以重放吗？

好像可以，都有回应

**Comment by horryruo** [comment]
而且重放之后，第二天的签到成功了。。

**Comment by horryruo** [comment]
应该是能弄的吧
